### ISSUE TITLE
Crash Browser -- IllegalStateException

### ISSUE THREAD

**Issue by moxie0** [WhisperSystems/Signal-Android#2507]
`````
java.lang.IllegalStateException: Couldn't read row 1799, col 0 from CursorWindow. Make sure the Cursor is initialized correctly before accessing data from it.
at android.database.CursorWindow.nativeGetLong(Native Method)
at android.database.CursorWindow.getLong(CursorWindow.java:512)
at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:220)
at android.support.v4.widget.CursorAdapter.getItem(CursorAdapter.java:213)
at org.thoughtcrime.securesms.ConversationAdapter.getItemViewType(ConversationAdapter.java:132)
at android.widget.AbsListView$RecycleBin.getScrapView(AbsListView.java:8821)
at android.widget.AbsListView.obtainView(AbsListView.java:2790)
at android.widget.ListView.makeAndAddView(ListView.java:1811)
at android.widget.ListView.fillDown(ListView.java:697)
at android.widget.ListView.fillSpecific(ListView.java:1366)
at android.widget.ListView.layoutChildren(ListView.java:1619)
at android.widget.AbsListView.onTouchMove(AbsListView.java:5314)
at android.widget.AbsListView.onTouchEvent(AbsListView.java:5180)
at android.view.View.dispatchTouchEvent(View.java:8281)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2471)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2194)
at android.widget.AbsListView.dispatchTouchEvent(AbsListView.java:5129)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2477)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2209)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2477)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2209)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2477)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2209)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2477)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2209)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2477)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2209)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2477)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2209)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2477)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2209)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2477)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2209)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2477)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2209)
at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2332)
at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1616)
at android.app.Activity.dispatchTouchEvent(Activity.java:2657)
at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2280)
at android.view.View.dispatchPointerEvent(View.java:8489)
at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4839)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4690)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4245)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4299)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4268)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4379)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4276)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4436)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4245)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4299)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4268)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4276)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4245)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6623)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6519)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6490)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6455)
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6703)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:138)
at android.os.Looper.loop(Looper.java:131)
at android.app.ActivityThread.main(ActivityThread.java:5731)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
at dalvik.system.NativeStart.main(Native Method)
`````

**Comment by mcginty** [comment]
closing since this should be in a better state after the partial conversation loading change
