### ISSUE TITLE
OOM: can't update group avatar

### ISSUE THREAD

**Issue by ghost** [WhisperSystems/Signal-Android#3084]
When i try to update the avatar, after selecting the pic from the gallery, i am displayed the page with the info about the group (members and photo), but the photo is the old one. I can't even crop the picture, it just exits.
https://gist.github.com/d1cca4426eaff1fe536f

**Comment by rhodey** [comment]
there are a bunch of out of memory exceptions in this log, which I expect are the root cause of this bug, but also a few other interesting exceptions too that @moxie0 or @mcginty probably understand better.

first OOM:
```
E/dalvikvm-heap(24127): Out of memory on a 19660816-byte allocation.
I/dalvikvm(24127): "main" prio=5 tid=1 RUNNABLE
I/dalvikvm(24127):   | group="main" sCount=0 dsCount=0 obj=0x40fb7508 self=0x40efd8a8
I/dalvikvm(24127):   | sysTid=24127 nice=0 sched=0/0 cgrp=[no-cpu-subsys] handle=1075855152
I/dalvikvm(24127):   | schedstat=( 773244781598 453929229835 1350017 ) utm=67648 stm=9676 core=1
I/dalvikvm(24127):   at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
I/dalvikvm(24127):   at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:621)
I/dalvikvm(24127):   at com.soundcloud.android.crop.CropImageActivity.c(CropImageActivity.java:134)
I/dalvikvm(24127):   at com.soundcloud.android.crop.CropImageActivity.onCreate(CropImageActivity.java:79)
I/dalvikvm(24127):   at android.app.Activity.performCreate(Activity.java:5047)
I/dalvikvm(24127):   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
I/dalvikvm(24127):   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2056)
I/dalvikvm(24127):   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2117)
I/dalvikvm(24127):   at android.app.ActivityThread.access$700(ActivityThread.java:134)
I/dalvikvm(24127):   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1218)
I/dalvikvm(24127):   at android.os.Handler.dispatchMessage(Handler.java:99)
I/dalvikvm(24127):   at android.os.Looper.loop(Looper.java:137)
I/dalvikvm(24127):   at android.app.ActivityThread.main(ActivityThread.java:4867)
I/dalvikvm(24127):   at java.lang.reflect.Method.invokeNative(Native Method)
I/dalvikvm(24127):   at java.lang.reflect.Method.invoke(Method.java:511)
I/dalvikvm(24127):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1007)
I/dalvikvm(24127):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:774)
I/dalvikvm(24127):   at dalvik.system.NativeStart.main(Native Method)
I/dalvikvm(24127): 
D/skia    (24127): --- decoder->decode returned false
D/AbsListView(24127): [unregisterDoubleTapMotionListener]
I/MotionRecognitionManager(24127):   .unregisterListener : / listener count = 0->0, ubvf 9budiwrd5ordgfl5BakTrklMrfo$,@,)a8-f+(
E/android-crop(24127): OOM reading image: null
E/android-crop(24127): java.lang.OutOfMemoryError
E/android-crop(24127): 	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
E/android-crop(24127): 	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:621)
E/android-crop(24127): 	at com.soundcloud.android.crop.CropImageActivity.c(CropImageActivity.java:134)
E/android-crop(24127): 	at com.soundcloud.android.crop.CropImageActivity.onCreate(CropImageActivity.java:79)
E/android-crop(24127): 	at android.app.Activity.performCreate(Activity.java:5047)
E/android-crop(24127): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
E/android-crop(24127): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2056)
E/android-crop(24127): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2117)
E/android-crop(24127): 	at android.app.ActivityThread.access$700(ActivityThread.java:134)
E/android-crop(24127): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1218)
E/android-crop(24127): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/android-crop(24127): 	at android.os.Looper.loop(Looper.java:137)
E/android-crop(24127): 	at android.app.ActivityThread.main(ActivityThread.java:4867)
E/android-crop(24127): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/android-crop(24127): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/android-crop(24127): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1007)
E/android-crop(24127): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:774)
E/android-crop(24127): 	at dalvik.system.NativeStart.main(Native Method)
```

other interesting traces:
```
W/TextSecureMessageSender(24127): org.whispersystems.textsecure.internal.push.exceptions.StaleDevicesException
W/TextSecureMessageSender(24127): 	at org.whispersystems.textsecure.internal.push.PushServiceSocket.makeBaseRequest(PushServiceSocket.java:485)
W/TextSecureMessageSender(24127): 	at org.whispersystems.textsecure.internal.push.PushServiceSocket.makeRequest(PushServiceSocket.java:434)
W/TextSecureMessageSender(24127): 	at org.whispersystems.textsecure.internal.push.PushServiceSocket.sendMessage(PushServiceSocket.java:157)
W/TextSecureMessageSender(24127): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.sendMessage(TextSecureMessageSender.java:245)
W/TextSecureMessageSender(24127): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.sendMessage(TextSecureMessageSender.java:221)
W/TextSecureMessageSender(24127): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.sendMessage(TextSecureMessageSender.java:149)
W/TextSecureMessageSender(24127): 	at org.thoughtcrime.securesms.jobs.PushGroupSendJob.deliver(PushGroupSendJob.java:157)
W/TextSecureMessageSender(24127): 	at org.thoughtcrime.securesms.jobs.PushGroupSendJob.onSend(PushGroupSendJob.java:83)
W/TextSecureMessageSender(24127): 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:39)
W/TextSecureMessageSender(24127): 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
W/TextSecureMessageSender(24127): 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
W/TextSecureMessageSender(24127): 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
```

```
W/PushGroupSendJob(24127): org.whispersystems.textsecure.api.push.exceptions.EncapsulatedExceptions
W/PushGroupSendJob(24127): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.sendMessage(TextSecureMessageSender.java:235)
W/PushGroupSendJob(24127): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.sendMessage(TextSecureMessageSender.java:149)
W/PushGroupSendJob(24127): 	at org.thoughtcrime.securesms.jobs.PushGroupSendJob.deliver(PushGroupSendJob.java:157)
W/PushGroupSendJob(24127): 	at org.thoughtcrime.securesms.jobs.PushGroupSendJob.onSend(PushGroupSendJob.java:83)
W/PushGroupSendJob(24127): 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:39)
W/PushGroupSendJob(24127): 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
W/PushGroupSendJob(24127): 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
W/PushGroupSendJob(24127): 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
```

```
W/ConversationActivity(24127): isManual Selection: false
W/ConversationActivity(24127): forceSms: false
W/ConversationActivity(24127): org.whispersystems.libaxolotl.InvalidMessageException: Message is empty!
W/ConversationActivity(24127): 	at org.thoughtcrime.securesms.ConversationActivity.getMessage(ConversationActivity.java:957)
W/ConversationActivity(24127): 	at org.thoughtcrime.securesms.ConversationActivity.sendTextMessage(ConversationActivity.java:1061)
W/ConversationActivity(24127): 	at org.thoughtcrime.securesms.ConversationActivity.sendMessage(ConversationActivity.java:1008)
W/ConversationActivity(24127): 	at org.thoughtcrime.securesms.ConversationActivity.access$2400(ConversationActivity.java:120)
W/ConversationActivity(24127): 	at org.thoughtcrime.securesms.ConversationActivity$SendButtonListener.onClick(ConversationActivity.java:1114)
W/ConversationActivity(24127): 	at android.view.View.performClick(View.java:4162)
W/ConversationActivity(24127): 	at android.view.View$PerformClick.run(View.java:17082)
W/ConversationActivity(24127): 	at android.os.Handler.handleCallback(Handler.java:615)
W/ConversationActivity(24127): 	at android.os.Handler.dispatchMessage(Handler.java:92)
W/ConversationActivity(24127): 	at android.os.Looper.loop(Looper.java:137)
W/ConversationActivity(24127): 	at android.app.ActivityThread.main(ActivityThread.java:4867)
W/ConversationActivity(24127): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/ConversationActivity(24127): 	at java.lang.reflect.Method.invoke(Method.java:511)
W/ConversationActivity(24127): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1007)
W/ConversationActivity(24127): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:774)
W/ConversationActivity(24127): 	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Mihahn** [comment]
I have the same problem and can't change the group avatar... Nexus 4, 5.1.1, TS 2.17.0

```
W/KeyCachingService( 2810): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
W/KeyCachingService( 2810): Incrementing activity count...
W/MessageRetrievalService( 2810): Active Count: 1
W/KeyCachingService( 2810): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
W/KeyCachingService( 2810): Decrementing activity count...
W/MessageRetrievalService( 2810): Active Count: 0
W/IInputConnectionWrapper( 2810): showStatusIcon on inactive InputConnection
W/KeyCachingService( 2810): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
W/KeyCachingService( 2810): Incrementing activity count...
W/MessageRetrievalService( 2810): Active Count: 1
W/KeyCachingService( 2810): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
W/KeyCachingService( 2810): Decrementing activity count...
W/MessageRetrievalService( 2810): Active Count: 0
D/skia ( 2810): --- decoder->buildTileIndex returned false
E/android-crop( 2810): Error cropping image: Image failed to decode using GIF decoder
E/android-crop( 2810): java.io.IOException: Image failed to decode using GIF decoder
E/android-crop( 2810): at android.graphics.BitmapRegionDecoder.nativeNewInstance(Native Method)
E/android-crop( 2810): at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:124)
E/android-crop( 2810): at com.soundcloud.android.crop.CropImageActivity.decodeRegionCrop(CropImageActivity.java:334)
E/android-crop( 2810): at com.soundcloud.android.crop.CropImageActivity.onSaveClicked(CropImageActivity.java:295)
E/android-crop( 2810): at com.soundcloud.android.crop.CropImageActivity.access$000(CropImageActivity.java:46)
E/android-crop( 2810): at com.soundcloud.android.crop.CropImageActivity$3.onClick(CropImageActivity.java:107)
E/android-crop( 2810): at android.view.View.performClick(View.java:4780)
E/android-crop( 2810): at android.view.View$PerformClick.run(View.java:19866)
E/android-crop( 2810): at android.os.Handler.handleCallback(Handler.java:739)
E/android-crop( 2810): at android.os.Handler.dispatchMessage(Handler.java:95)
E/android-crop( 2810): at android.os.Looper.loop(Looper.java:135)
E/android-crop( 2810): at android.app.ActivityThread.main(ActivityThread.java:5254)
E/android-crop( 2810): at java.lang.reflect.Method.invoke(Native Method)
E/android-crop( 2810): at java.lang.reflect.Method.invoke(Method.java:372)
E/android-crop( 2810): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/android-crop( 2810): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/android-crop( 2810): at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
W/KeyCachingService( 2810): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
```

**Comment by agrajaghh** [comment]
@Mihahn looks like another error with gif images..
`E/android-crop( 2810): Error cropping image: Image failed to decode using GIF decoder`

could you delete this one here and open another issue for that please?

**Comment by riyapenn** [comment]
Is this still an issue?

**Comment by heliocarbex** [comment]
I have tried to change the picture in a group in my phone (Lenovo K5, Android 5.1.1, Signal 3.21.3) and doesn't work. The file has 34,15 KB and 355 x 355 pixels.
