### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by moxie0** [WhisperSystems/Signal-Android#3092]
`````
E/AndroidRuntime( 1086): java.lang.OutOfMemoryError: bitmap size exceeds VM budget
E/AndroidRuntime( 1086): 	at android.graphics.Bitmap.nativeCreate(Native Method)
E/AndroidRuntime( 1086): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:477)
E/AndroidRuntime( 1086): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:444)
E/AndroidRuntime( 1086): 	at org.thoughtcrime.securesms.util.BitmapUtil.rotateBitmap(BitmapUtil.java:200)
E/AndroidRuntime( 1086): 	at org.thoughtcrime.securesms.util.BitmapUtil.fixOrientation(BitmapUtil.java:191)
E/AndroidRuntime( 1086): 	at org.thoughtcrime.securesms.util.BitmapUtil.createScaledBitmap(BitmapUtil.java:97)
E/AndroidRuntime( 1086): 	at org.thoughtcrime.securesms.util.BitmapUtil.createScaledBitmap(BitmapUtil.java:86)
E/AndroidRuntime( 1086): 	at org.thoughtcrime.securesms.util.BitmapUtil.createScaledBytes(BitmapUtil.java:45)
E/AndroidRuntime( 1086): 	at org.thoughtcrime.securesms.mms.MediaConstraints.getResizedMedia(MediaConstraints.java:63)
E/AndroidRuntime( 1086): 	at org.thoughtcrime.securesms.jobs.SendJob.getResizedPartData(SendJob.java:93)
E/AndroidRuntime( 1086): 	at org.thoughtcrime.securesms.jobs.SendJob.getResolvedPart(SendJob.java:73)
E/AndroidRuntime( 1086): 	at org.thoughtcrime.securesms.jobs.SendJob.getResolvedMessage(SendJob.java:51)
E/AndroidRuntime( 1086): 	at org.thoughtcrime.securesms.jobs.PushMediaSendJob.deliver(PushMediaSendJob.java:107)
E/AndroidRuntime( 1086): 	at org.thoughtcrime.securesms.jobs.PushMediaSendJob.onSend(PushMediaSendJob.java:66)
E/AndroidRuntime( 1086): 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:39)
E/AndroidRuntime( 1086): 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
E/AndroidRuntime( 1086): 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
E/AndroidRuntime( 1086): 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
`````

**Comment by moxie0** [comment]
`````
E/AndroidRuntime(  684): FATAL EXCEPTION: AsyncTask #5
E/AndroidRuntime(  684): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime(  684): 	at android.os.AsyncTask$3.done(AsyncTask.java:200)
E/AndroidRuntime(  684): 	at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:274)
E/AndroidRuntime(  684): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:125)
E/AndroidRuntime(  684): 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:308)
E/AndroidRuntime(  684): 	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
E/AndroidRuntime(  684): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
E/AndroidRuntime(  684): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
E/AndroidRuntime(  684): 	at java.lang.Thread.run(Thread.java:1019)
E/AndroidRuntime(  684): Caused by: java.lang.OutOfMemoryError: bitmap size exceeds VM budget
E/AndroidRuntime(  684): 	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
E/AndroidRuntime(  684): 	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:470)
E/AndroidRuntime(  684): 	at org.thoughtcrime.securesms.util.BitmapUtil.createScaledBitmap(BitmapUtil.java:146)
E/AndroidRuntime(  684): 	at org.thoughtcrime.securesms.util.BitmapUtil.createScaledBitmap(BitmapUtil.java:110)
E/AndroidRuntime(  684): 	at org.thoughtcrime.securesms.util.BitmapUtil.createScaledBitmap(BitmapUtil.java:101)
E/AndroidRuntime(  684): 	at org.thoughtcrime.securesms.util.BitmapUtil.createScaledBitmap(BitmapUtil.java:91)
E/AndroidRuntime(  684): 	at org.thoughtcrime.securesms.util.BitmapUtil.createScaledBitmap(BitmapUtil.java:80)
E/AndroidRuntime(  684): 	at org.thoughtcrime.securesms.MediaPreviewActivity$1.doInBackground(MediaPreviewActivity.java:199)
E/AndroidRuntime(  684): 	at org.thoughtcrime.securesms.MediaPreviewActivity$1.doInBackground(MediaPreviewActivity.java:191)
E/AndroidRuntime(  684): 	at android.os.AsyncTask$2.call(AsyncTask.java:185)
E/AndroidRuntime(  684): 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:306)
E/AndroidRuntime(  684): 	... 4 more
`````

**Comment by mcginty** [comment]
closing since this is old and Glide helped resolve most of these
