### ISSUE TITLE
Problem updating group avatar

### ISSUE THREAD

**Issue by Mihahn** [WhisperSystems/Signal-Android#3381]
I can't change the group avatar of a just created group. The image is a .jpg and Mimetype: image/gif. 
Other images (.png - Mimetype image/webp and .jpg - Mimetype image/webp) do work!

Nexus 4, 5.1.1, TS 2.17.0

```
W/KeyCachingService( 2810): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
W/KeyCachingService( 2810): Incrementing activity count...
W/MessageRetrievalService( 2810): Active Count: 1
W/KeyCachingService( 2810): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
W/KeyCachingService( 2810): Decrementing activity count...
W/MessageRetrievalService( 2810): Active Count: 0
W/IInputConnectionWrapper( 2810): showStatusIcon on inactive InputConnection
W/KeyCachingService( 2810): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
W/KeyCachingService( 2810): Incrementing activity count...
W/MessageRetrievalService( 2810): Active Count: 1
W/KeyCachingService( 2810): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
W/KeyCachingService( 2810): Decrementing activity count...
W/MessageRetrievalService( 2810): Active Count: 0
D/skia ( 2810): --- decoder->buildTileIndex returned false
E/android-crop( 2810): Error cropping image: Image failed to decode using GIF decoder
E/android-crop( 2810): java.io.IOException: Image failed to decode using GIF decoder
E/android-crop( 2810): at android.graphics.BitmapRegionDecoder.nativeNewInstance(Native Method)
E/android-crop( 2810): at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:124)
E/android-crop( 2810): at com.soundcloud.android.crop.CropImageActivity.decodeRegionCrop(CropImageActivity.java:334)
E/android-crop( 2810): at com.soundcloud.android.crop.CropImageActivity.onSaveClicked(CropImageActivity.java:295)
E/android-crop( 2810): at com.soundcloud.android.crop.CropImageActivity.access$000(CropImageActivity.java:46)
E/android-crop( 2810): at com.soundcloud.android.crop.CropImageActivity$3.onClick(CropImageActivity.java:107)
E/android-crop( 2810): at android.view.View.performClick(View.java:4780)
E/android-crop( 2810): at android.view.View$PerformClick.run(View.java:19866)
E/android-crop( 2810): at android.os.Handler.handleCallback(Handler.java:739)
E/android-crop( 2810): at android.os.Handler.dispatchMessage(Handler.java:95)
E/android-crop( 2810): at android.os.Looper.loop(Looper.java:135)
E/android-crop( 2810): at android.app.ActivityThread.main(ActivityThread.java:5254)
E/android-crop( 2810): at java.lang.reflect.Method.invoke(Native Method)
E/android-crop( 2810): at java.lang.reflect.Method.invoke(Method.java:372)
E/android-crop( 2810): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/android-crop( 2810): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/android-crop( 2810): at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
W/KeyCachingService( 2810): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
```

[Full debug log](https://gist.github.com/anonymous/9054641f3408b3a168fc)

**Comment by mcginty** [comment]
Looks like our cropping library doesn't have GIF support.

**Comment by 2-4601** [comment]
Closing in favour of #3907 (it has better title :)
