### ISSUE TITLE
Deleted images still selectable

### ISSUE THREAD

**Issue by rmueller83** [WhisperSystems/Signal-Android#4055]
I often download an image in Chrome, send it via instant messenger and afterwards delete it.

In TextSecure, the deleted images are still selectable after deletion. Immediately after deletion there is still a thumbnail visible. If I reboot my phone, the thumbnail is gone and I only see empty boxes:

![screenshot_2015-09-09-22-15-40](https://cloud.githubusercontent.com/assets/2698076/9773174/1d2d1a58-5741-11e5-84fb-084924adb01f.png)

So does TextSecure use some kind of persistent cache here? In the log I get a stack trace:

Device  : motorola XT1032 (falcon_retde)
Android : 5.0.2 (1, LXB22.46-28.1)
Memory  : 51M (0.05% used, 96M max)
Memclass: 96
OS Host : ilclbld72
App     : TextSecure 2.26.2

    ws.com.google.android.mms.MmsException: java.io.FileNotFoundException: No such file or directory
    	at org.thoughtcrime.securesms.database.PartDatabase.writePartData(PartDatabase.java:417)
    	at org.thoughtcrime.securesms.database.PartDatabase.insertPart(PartDatabase.java:471)
    	at org.thoughtcrime.securesms.database.PartDatabase.insertParts(PartDatabase.java:241)
    	at org.thoughtcrime.securesms.database.MmsDatabase.insertMediaMessage(MmsDatabase.java:807)
    	at org.thoughtcrime.securesms.database.MmsDatabase.insertMessageOutbox(MmsDatabase.java:763)
    	at org.thoughtcrime.securesms.sms.MessageSender.send(MessageSender.java:103)
    	at org.thoughtcrime.securesms.ConversationActivity$21.doInBackground(ConversationActivity.java:1217)
    	at org.thoughtcrime.securesms.ConversationActivity$21.doInBackground(ConversationActivity.java:1214)
    	at android.os.AsyncTask$2.call(AsyncTask.java:288)
    	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    	at java.lang.Thread.run(Thread.java:818)
    Caused by: java.io.FileNotFoundException: No such file or directory
    	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
    	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:689)
    	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1080)
    	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:921)
    	at android.content.ContentResolver.openInputStream(ContentResolver.java:646)
    	at org.thoughtcrime.securesms.mms.PartAuthority.getPartStream(PartAuthority.java:52)
    	at org.thoughtcrime.securesms.database.PartDatabase.writePartData(PartDatabase.java:411)
    	... 13 more

**Comment by 2-4601** [comment]
It depends on how you delete them. E.g. If I remove a pic with the Google Photos app (on Nexus 4, stock 5.1.1) it doesn't show up in the TS attachment selection anymore. But if I use a file manager to delete then a thumbnail or a ghost thumbnail might still show up in TS.

Related or duplicate of #3053.

**Comment by rmueller83** [comment]
I delete them from within the Motorola Gallery app ( https://play.google.com/store/apps/details?id=com.motorola.MotGallery2 ). There as well as in the Google Photo app and in WhatsApp they are not visible - everything is fine there.

**Comment by rmueller83** [comment]
Does not seem to occur any more.
