### ISSUE TITLE
Crash in contact selection view

### ISSUE THREAD

**Issue by dcherian** [WhisperSystems/Signal-Android#4666]
Tapped on FAB in conversation list screen and signal crashed.

https://gist.github.com/dddac80d2dd2670a2294

**Comment by dcherian** [comment]
```
E/MessageQueue-JNI(31956): java.lang.IllegalStateException: Cursor should not be null here.
E/MessageQueue-JNI(31956): at org.thoughtcrime.securesms.contacts.ContactSelectionListAdapter.getCursorAtPositionOrThrow(ContactSelectionListAdapter.java:184)
E/MessageQueue-JNI(31956): at org.thoughtcrime.securesms.contacts.ContactSelectionListAdapter.getHeaderString(ContactSelectionListAdapter.java:164)
E/MessageQueue-JNI(31956): at org.thoughtcrime.securesms.contacts.ContactSelectionListAdapter.getBubbleText(ContactSelectionListAdapter.java:145)
E/MessageQueue-JNI(31956): at org.thoughtcrime.securesms.components.RecyclerViewFastScroller.setRecyclerViewPosition(RecyclerViewFastScroller.java:159)
E/MessageQueue-JNI(31956): at org.thoughtcrime.securesms.components.RecyclerViewFastScroller.onTouchEvent(RecyclerViewFastScroller.java:109)
E/MessageQueue-JNI(31956): at android.view.View.dispatchTouchEvent(View.java:7736)
E/MessageQueue-JNI(31956): at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2212)
E/MessageQueue-JNI(31956): at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1945)
E/MessageQueue-JNI(31956): at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
E/MessageQueue-JNI(31956): at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
E/MessageQueue-JNI(31956): at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
E/MessageQueue-JNI(31956): at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
E/MessageQueue-JNI(31956): at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
E/MessageQueue-JNI(31956): at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
E/MessageQueue-JNI(31956): at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
E/MessageQueue-JNI(31956): at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
E/MessageQueue-JNI(31956): at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
E/MessageQueue-JNI(31956): at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
E/MessageQueue-JNI(31956): at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
E/MessageQueue-JNI(31956): at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
E/MessageQueue-JNI(31956): at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
E/MessageQueue-JNI(31956): at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
E/MessageQueue-JNI(31956): at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2068)
E/MessageQueue-JNI(31956): at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1515)
E/MessageQueue-JNI(31956): at android.app.Activity.dispatchTouchEvent(Activity.java:2466)
E/MessageQueue-JNI(31956): at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:59)
E/MessageQueue-JNI(31956): at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:59)
E/MessageQueue-JNI(31956): at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2016)
E/MessageQueue-JNI(31956): at android.view.View.dispatchPointerEvent(View.java:7916)
E/MessageQueue-JNI(31956): at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4023)
E/MessageQueue-JNI(31956): at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3902)
E/MessageQueue-JNI(31956): at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3452)
E/MessageQueue-JNI(31956): at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3502)
E/MessageQueue-JNI(31956): at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3471)
E/MessageQueue-JNI(31956): at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3578)
E/MessageQueue-JNI(31956): at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3479)
E/MessageQueue-JNI(31956): at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3635)
E/MessageQueue-JNI(31956): at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3452)
E/MessageQueue-JNI(31956): at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3502)
E/MessageQueue-JNI(31956): at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3471)
E/MessageQueue-JNI(31956): at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3479)
E/MessageQueue-JNI(31956): at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3452)
E/MessageQueue-JNI(31956): at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5657)
E/MessageQueue-JNI(31956): at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5588)
E/MessageQueue-JNI(31956): at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5559)
E/MessageQueue-JNI(31956): at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5737)
E/MessageQueue-JNI(31956): at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
E/MessageQueue-JNI(31956): at android.os.MessageQueue.nativePollOnce(Native Method)
E/MessageQueue-JNI(31956): at android.os.MessageQueue.next(MessageQueue.java:138)
E/MessageQueue-JNI(31956): 
```

**Comment by dcherian** [comment]
```
E/AndroidRuntime(31956): FATAL EXCEPTION: main
E/AndroidRuntime(31956): Process: org.thoughtcrime.securesms, PID: 31956
E/AndroidRuntime(31956): java.lang.IllegalStateException: Cursor should not be null here.
E/AndroidRuntime(31956): at org.thoughtcrime.securesms.contacts.ContactSelectionListAdapter.getCursorAtPositionOrThrow(ContactSelectionListAdapter.java:184)
E/AndroidRuntime(31956): at org.thoughtcrime.securesms.contacts.ContactSelectionListAdapter.getHeaderString(ContactSelectionListAdapter.java:164)
E/AndroidRuntime(31956): at org.thoughtcrime.securesms.contacts.ContactSelectionListAdapter.getBubbleText(ContactSelectionListAdapter.java:145)
E/AndroidRuntime(31956): at org.thoughtcrime.securesms.components.RecyclerViewFastScroller.setRecyclerViewPosition(RecyclerViewFastScroller.java:159)
E/AndroidRuntime(31956): at org.thoughtcrime.securesms.components.RecyclerViewFastScroller.onTouchEvent(RecyclerViewFastScroller.java:109)
E/AndroidRuntime(31956): at android.view.View.dispatchTouchEvent(View.java:7736)
E/AndroidRuntime(31956): at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2212)
E/AndroidRuntime(31956): at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1945)
E/AndroidRuntime(31956): at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
E/AndroidRuntime(31956): at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
E/AndroidRuntime(31956): at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
E/AndroidRuntime(31956): at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
E/AndroidRuntime(31956): at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
E/AndroidRuntime(31956): at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
E/AndroidRuntime(31956): at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
E/AndroidRuntime(31956): at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
E/AndroidRuntime(31956): at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
E/AndroidRuntime(31956): at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
E/AndroidRuntime(31956): at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
E/AndroidRuntime(31956): at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
E/AndroidRuntime(31956): at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
E/AndroidRuntime(31956): at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
E/AndroidRuntime(31956): at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2068)
E/AndroidRuntime(31956): at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1515)
E/AndroidRuntime(31956): at android.app.Activity.dispatchTouchEvent(Activity.java:2466)
E/AndroidRuntime(31956): at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:59)
E/AndroidRuntime(31956): at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:59)
E/AndroidRuntime(31956): at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2016)
E/AndroidRuntime(31956): at android.view.View.dispatchPointerEvent(View.java:7916)
E/AndroidRuntime(31956): at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4023)
E/AndroidRuntime(31956): at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3902)
E/AndroidRuntime(31956): at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3452)
E/AndroidRuntime(31956): at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3502)
E/AndroidRuntime(31956): at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3471)
E/AndroidRuntime(31956): at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3578)
E/AndroidRuntime(31956): at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3479)
E/AndroidRuntime(31956): at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3635)
E/AndroidRuntime(31956): at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3452)
E/AndroidRuntime(31956): at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3502)
E/AndroidRuntime(31956): at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3471)
E/AndroidRuntime(31956): at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3479)
E/AndroidRuntime(31956): at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3452)
E/AndroidRuntime(31956): at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5657)
E/AndroidRuntime(31956): at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5588)
E/AndroidRuntime(31956): at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5559)
E/AndroidRuntime(31956): at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5737)
E/AndroidRuntime(31956): at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
E/AndroidRuntime(31956): at android.os.MessageQueue.nativePollOnce(Nati
```

**Comment by mcginty** [comment]
Ah, good catch. Reproducible if I quickly try to scroll *right* after opening the new conversation view since the adapter isn't loaded with data.
