### ISSUE TITLE
Scrolling to top of conversation with more than 500 messages crashes Signal

### ISSUE THREAD

**Issue by cascheberg** [WhisperSystems/Signal-Android#4667]
Scrolling to the top of a conversation that has more than 500 messages crashes Signal. This is a regression.

Edit: as @bartz1 said, it crashes before you reach "load more messages".

Signal v3.5.0 on Nexus 4, stock Android 5.1.1

```
FATAL EXCEPTION: main
Process: org.thoughtcrime.securesms, PID: 27115
java.lang.IllegalStateException: couldn't move cursor to position 500
   at org.thoughtcrime.securesms.database.CursorRecyclerViewAdapter.moveToPositionOrThrow(CursorRecyclerViewAdapter.java:184)
   at org.thoughtcrime.securesms.database.CursorRecyclerViewAdapter.getItemId(CursorRecyclerViewAdapter.java:167)
   at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4376)
   at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4326)
   at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1955)
   at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1364)
   at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1327)
   at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1155)
   at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1012)
   at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:3777)
   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
   at android.view.Choreographer.doCallbacks(Choreographer.java:580)
   at android.view.Choreographer.doFrame(Choreographer.java:549)
   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
   at android.os.Handler.handleCallback(Handler.java:739)
   at android.os.Handler.dispatchMessage(Handler.java:95)
   at android.os.Looper.loop(Looper.java:135)
   at android.app.ActivityThread.main(ActivityThread.java:5254)
   at java.lang.reflect.Method.invoke(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:372)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by bartz1** [comment]
Yup, happens to me too. Can't even reach the top button saying "load more messages"

**Comment by McLoo** [comment]
Me too
https://gist.github.com/f7e006b1aad82dd1030d

**Comment by Natanji** [comment]
This is happening again, I am seeing this behaviour in Signal 4.24.1 - please reopen this @mcginty.
 
Debug log: https://debuglogs.org/046a9e96d9bd268941e7ba9d7cc0816a00e6d485d29dd4d906aaa52e06ef466d
