### ISSUE TITLE
Can't mute group

### ISSUE THREAD

**Issue by bartz1** [WhisperSystems/Signal-Android#4674]
Crashes when I try mute groups in signal 3.5. Can't post debug log now though.

**Comment by moxie0** [comment]
can't do anything without a debug log

On 11/22/2015 09:33 AM, bartz1 wrote:
> Crashes when I try mute groups in signal 3.5. Can't post debug log now
> though.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-Android/issues/4674>.
> 

-- 
http://www.thoughtcrime.org

**Comment by McLoo** [comment]
https://gist.github.com/dfb09fc7252bfdd3b96d

**Comment by bartz1** [comment]
You can reproduce it

**Comment by mcginty** [comment]
how is this me?

```
E/AndroidRuntime(22930): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.preference.Preference.onPrepareForRemoval()' on a null object reference
E/AndroidRuntime(22930): 	at android.preference.PreferenceGroup.removePreferenceInt(PreferenceGroup.java:195)
E/AndroidRuntime(22930): 	at android.preference.PreferenceGroup.removePreference(PreferenceGroup.java:188)
E/AndroidRuntime(22930): 	at org.thoughtcrime.securesms.RecipientPreferenceActivity$RecipientPreferenceFragment.setSummaries(RecipientPreferenceActivity.java:223)
E/AndroidRuntime(22930): 	at org.thoughtcrime.securesms.RecipientPreferenceActivity$RecipientPreferenceFragment.access$700(RecipientPreferenceActivity.java:144)
E/AndroidRuntime(22930): 	at org.thoughtcrime.securesms.RecipientPreferenceActivity$RecipientPreferenceFragment$MuteClickedListener.handleMute(RecipientPreferenceActivity.java:337)
E/AndroidRuntime(22930): 	at org.thoughtcrime.securesms.RecipientPreferenceActivity$RecipientPreferenceFragment$MuteClickedListener.onPreferenceClick(RecipientPreferenceActivity.java:324)
E/AndroidRuntime(22930): 	at android.preference.Preference.performClick(Preference.java:985)
E/AndroidRuntime(22930): 	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:214)
E/AndroidRuntime(22930): 	at android.widget.AdapterView.performItemClick(AdapterView.java:305)
E/AndroidRuntime(22930): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1146)
E/AndroidRuntime(22930): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3057)
E/AndroidRuntime(22930): 	at android.widget.AbsListView$3.run(AbsListView.java:3864)
E/AndroidRuntime(22930): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(22930): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(22930): 	at android.os.Looper.loop(Looper.java:211)
E/AndroidRuntime(22930): 	at android.app.ActivityThread.main(ActivityThread.java:5389)
E/AndroidRuntime(22930): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(22930): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(22930): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
E/AndroidRuntime(22930): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
E/AndroidRuntime(22930): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:114)
```

**Comment by McLoo** [comment]
Maybe he referred to the other  500 cursor pos error

**Comment by moxie0** [comment]
oh I just saw the cursor exception. looks like it's actually @agrajaghh 's change.

**Comment by agrajaghh** [comment]
ooops, shame on me :grimacing: 

will open a PR...
