### ISSUE TITLE
Signal calls don't work sometimes

### ISSUE THREAD

**Issue by dcherian** [WhisperSystems/Signal-Android#4835]
Signal 3.7.0, Moto G, Android 4.4.4 Xposed

Two times now, Signal has refused to make a call. I tap the call button, the screen says "DIALLING" and then changes to "CALL DISCONNECTED" quite quickly. If I try calling again, all I get is a white screen with a blue bar on top saying Signal call. If I force close and retry, it then works again.

Two logs:
https://gist.github.com/df44177f2aed4257b98b
https://gist.github.com/3fd018cac7f505bb771d

**Comment by Dyras** [comment]
I have a Moto G3 and I can confirm that this is happening on stock for me. Well, minus the white screen part. I'll see if I can get a log the next time it happens.

**Comment by 2-4601** [comment]
My case is not that similar with the original description but the logs look very similar.

I called with my Huawei device to my Nexus 4 which was in the locked screen state. It took a while (~20 seconds) for the Nexus 4 to start ringing. And when it did, I answered, but the call was not established. Huawei just showed ringing and after ~10s it said "recipient unavailable" and call was disconnected automatically on both devices. Both are running 3.14.2.

This happens moderately often when the recipient device is in the lock screen state. Is it just some timeout on the server side if establishing the call takes too long?

Log from the recipient device (Nexus 4):
https://gist.github.com/anonymous/8f958ef1f8fcc9725542
```
W/RedPhone( 4982): Got message from service: CALL_DISCONNECTED
W/RedPhone( 4982): handleTerminate called
W/RedPhone( 4982): Termination Stack:
W/RedPhone( 4982): java.lang.Exception
W/RedPhone( 4982): 	at org.thoughtcrime.redphone.RedPhone.handleTerminate(RedPhone.java:191)
W/RedPhone( 4982): 	at org.thoughtcrime.redphone.RedPhone.onEventMainThread(RedPhone.java:319)
W/RedPhone( 4982): 	at java.lang.reflect.Method.invoke(Native Method)
W/RedPhone( 4982): 	at java.lang.reflect.Method.invoke(Method.java:372)
W/RedPhone( 4982): 	at de.greenrobot.event.EventBus.invokeSubscriber(EventBus.java:498)
W/RedPhone( 4982): 	at de.greenrobot.event.EventBus.invokeSubscriber(EventBus.java:492)
W/RedPhone( 4982): 	at de.greenrobot.event.HandlerPoster.handleMessage(HandlerPoster.java:67)
W/RedPhone( 4982): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/RedPhone( 4982): 	at android.os.Looper.loop(Looper.java:135)
W/RedPhone( 4982): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
W/RedPhone( 4982): 	at java.lang.reflect.Method.invoke(Native Method)
W/RedPhone( 4982): 	at java.lang.reflect.Method.invoke(Method.java:372)
W/RedPhone( 4982): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
W/RedPhone( 4982): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
W/RedPhoneService( 4982): termination stack
W/RedPhoneService( 4982): java.lang.Exception
W/RedPhoneService( 4982): 	at org.thoughtcrime.redphone.RedPhoneService.terminate(RedPhoneService.java:364)
W/RedPhoneService( 4982): 	at org.thoughtcrime.redphone.RedPhoneService.notifyCallDisconnected(RedPhoneService.java:439)
W/RedPhoneService( 4982): 	at org.thoughtcrime.redphone.call.SignalManager$SignalListenerTask.run(SignalManager.java:66)
W/RedPhoneService( 4982): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/RedPhoneService( 4982): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/RedPhoneService( 4982): 	at java.lang.Thread.run(Thread.java:818)
D/LockManager( 4982): Entered Lock State: PARTIAL
```

As a bonus, here's one more log when an iOS device tried to call me earlier. This case prompted me to look into this in the first place.
https://gist.github.com/anonymous/51539a8dc93f92bf7a4a
```
W/RedPhone( 4982): Got message from service: CALL_DISCONNECTED
W/RedPhone( 4982): handleTerminate called
W/RedPhone( 4982): Termination Stack:
W/RedPhone( 4982): java.lang.Exception
W/RedPhone( 4982): 	at org.thoughtcrime.redphone.RedPhone.handleTerminate(RedPhone.java:191)
W/RedPhone( 4982): 	at org.thoughtcrime.redphone.RedPhone.onEventMainThread(RedPhone.java:319)
W/RedPhone( 4982): 	at java.lang.reflect.Method.invoke(Native Method)
W/RedPhone( 4982): 	at java.lang.reflect.Method.invoke(Method.java:372)
W/RedPhone( 4982): 	at de.greenrobot.event.EventBus.invokeSubscriber(EventBus.java:498)
W/RedPhone( 4982): 	at de.greenrobot.event.EventBus.invokeSubscriber(EventBus.java:492)
W/RedPhone( 4982): 	at de.greenrobot.event.HandlerPoster.handleMessage(HandlerPoster.java:67)
W/RedPhone( 4982): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/RedPhone( 4982): 	at android.os.Looper.loop(Looper.java:135)
W/RedPhone( 4982): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
W/RedPhone( 4982): 	at java.lang.reflect.Method.invoke(Native Method)
W/RedPhone( 4982): 	at java.lang.reflect.Method.invoke(Method.java:372)
W/RedPhone( 4982): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
W/RedPhone( 4982): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
W/RedPhoneService( 4982): termination stack
W/RedPhoneService( 4982): java.lang.Exception
W/RedPhoneService( 4982): 	at org.thoughtcrime.redphone.RedPhoneService.terminate(RedPhoneService.java:364)
W/RedPhoneService( 4982): 	at org.thoughtcrime.redphone.RedPhoneService.notifyCallDisconnected(RedPhoneService.java:439)
W/RedPhoneService( 4982): 	at org.thoughtcrime.redphone.call.SignalManager$SignalListenerTask.run(SignalManager.java:66)
W/RedPhoneService( 4982): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/RedPhoneService( 4982): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/RedPhoneService( 4982): 	at java.lang.Thread.run(Thread.java:818)
D/LockManager( 4982): Entered Lock State: PARTIAL
```

**Comment by dcherian** [comment]
Closing because this is a redphone bug.
