### ISSUE TITLE
SVG support (and a critical bug)

### ISSUE THREAD

**Issue by exploide** [WhisperSystems/Signal-Android#5046]
SVG attachment support in Signal-Android would be nice. Sending and receiving SVG files from Signal-Desktop works great, but on the Android client, they are not previewed and cannot be opened.

**Now the critical part**:
Even on the Android client, it is possible to select SVG files as image attachments. But when sending them, the app crashes and now I'm not able to open Signal-Andoid again. Each time I try to open the app, it crashes immediately.

**Comment by 2-4601** [comment]
Tested this by self-sending an SVG to myself (too afraid to try sending others:)
Doesn't crash for me but SVGs definitely don't work:
```
W/DecryptableStreamLocalUriFetcher( 1686): java.io.IOException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Cannot apply transformation on width: -1 or height: -1 less than or equal to zero and not Target.SIZE_ORIGINAL
W/DecryptableStreamLocalUriFetcher( 1686): 	at org.thoughtcrime.securesms.database.AttachmentDatabase.getThumbnailStream(AttachmentDatabase.java:139)
W/DecryptableStreamLocalUriFetcher( 1686): 	at org.thoughtcrime.securesms.mms.PartAuthority.getAttachmentStream(PartAuthority.java:52)
W/DecryptableStreamLocalUriFetcher( 1686): 	at org.thoughtcrime.securesms.mms.DecryptableStreamLocalUriFetcher.loadResource(DecryptableStreamLocalUriFetcher.java:32)
W/DecryptableStreamLocalUriFetcher( 1686): 	at org.thoughtcrime.securesms.mms.DecryptableStreamLocalUriFetcher.loadResource(DecryptableStreamLocalUriFetcher.java:16)
W/DecryptableStreamLocalUriFetcher( 1686): 	at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:44)
W/DecryptableStreamLocalUriFetcher( 1686): 	at com.bumptech.glide.load.model.ImageVideoModelLoader$ImageVideoFetcher.loadData(ImageVideoModelLoader.java:70)
W/DecryptableStreamLocalUriFetcher( 1686): 	at com.bumptech.glide.load.model.ImageVideoModelLoader$ImageVideoFetcher.loadData(ImageVideoModelLoader.java:53)
W/DecryptableStreamLocalUriFetcher( 1686): 	at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:170)
W/DecryptableStreamLocalUriFetcher( 1686): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128)
W/DecryptableStreamLocalUriFetcher( 1686): 	at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
W/DecryptableStreamLocalUriFetcher( 1686): 	at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
W/DecryptableStreamLocalUriFetcher( 1686): 	at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
W/DecryptableStreamLocalUriFetcher( 1686): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
W/DecryptableStreamLocalUriFetcher( 1686): 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
W/DecryptableStreamLocalUriFetcher( 1686): 	at java.util.concurrent.FutureTask.run(FutureTask.java:137)
W/DecryptableStreamLocalUriFetcher( 1686): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
W/DecryptableStreamLocalUriFetcher( 1686): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
W/DecryptableStreamLocalUriFetcher( 1686): 	at java.lang.Thread.run(Thread.java:856)
W/DecryptableStreamLocalUriFetcher( 1686): 	at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
W/DecryptableStreamLocalUriFetcher( 1686): Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Cannot apply transformation on width: -1 or height: -1 less than or equal to zero and not Target.SIZE_ORIGINAL
W/DecryptableStreamLocalUriFetcher( 1686): 	at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:223)
W/DecryptableStreamLocalUriFetcher( 1686): 	at java.util.concurrent.FutureTask.get(FutureTask.java:82)
W/DecryptableStreamLocalUriFetcher( 1686): 	at org.thoughtcrime.securesms.database.AttachmentDatabase.getThumbnailStream(AttachmentDatabase.java:131)
W/DecryptableStreamLocalUriFetcher( 1686): 	... 18 more
W/DecryptableStreamLocalUriFetcher( 1686): Caused by: java.lang.IllegalArgumentException: Cannot apply transformation on width: -1 or height: -1 less than or equal to zero and not Target.SIZE_ORIGINAL
W/DecryptableStreamLocalUriFetcher( 1686): 	at com.bumptech.glide.load.resource.bitmap.BitmapTransformation.transform(BitmapTransformation.java:48)
W/DecryptableStreamLocalUriFetcher( 1686): 	at org.thoughtcrime.securesms.util.BitmapUtil.createScaledBitmapInto(BitmapUtil.java:104)
W/DecryptableStreamLocalUriFetcher( 1686): 	at org.thoughtcrime.securesms.util.BitmapUtil.createScaledBitmap(BitmapUtil.java:80)
W/DecryptableStreamLocalUriFetcher( 1686): 	at org.thoughtcrime.securesms.util.MediaUtil.generateImageThumbnail(MediaUtil.java:55)
W/DecryptableStreamLocalUriFetcher( 1686): 	at org.thoughtcrime.securesms.util.MediaUtil.generateThumbnail(MediaUtil.java:39)
W/DecryptableStreamLocalUriFetcher( 1686): 	at org.thoughtcrime.securesms.database.AttachmentDatabase$ThumbnailFetchCallable.call(AttachmentDatabase.java:530)
W/DecryptableStreamLocalUriFetcher( 1686): 	at org.thoughtcrime.securesms.database.AttachmentDatabase$ThumbnailFetchCallable.call(AttachmentDatabase.java:506)
W/DecryptableStreamLocalUriFetcher( 1686): 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
W/DecryptableStreamLocalUriFetcher( 1686): 	at java.util.concurrent.FutureTask.run(FutureTask.java:137)
W/DecryptableStreamLocalUriFetcher( 1686): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
W/DecryptableStreamLocalUriFetcher( 1686): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
W/DecryptableStreamLocalUriFetcher( 1686): 	at java.lang.Thread.run(Thread.java:856)
```
3.9.1, Huawei U8800, Android 4.0.4

**Comment by exploide** [comment]
Of course, here it is:

```
01-09 13:59:30.263: I/Timeline(952): Timeline: Activity_launch_request id:org.thoughtcrime.securesms time:693238
01-09 13:59:30.264: I/ActivityManager(525): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.thoughtcrime.securesms/.RoutingActivity bnds=[327,849][427,969] (has extras)} from uid 10016 on display 0
01-09 13:59:30.266: V/WindowManager(525): addAppToken: AppWindowToken{2999745c token=Token{224f02cf ActivityRecord{6cec72e u0 org.thoughtcrime.securesms/.RoutingActivity t7081}}} to stack=1 task=7081 at 0
01-09 13:59:30.274: V/WindowManager(525): Adding window Window{1a727cc7 u0 Starting org.thoughtcrime.securesms} at 2 of 4 (after Window{11501c3f u0 com.cyanogenmod.trebuchet/com.android.launcher3.Launcher})
01-09 13:59:30.382: I/ActivityManager(525): Start proc 4504:org.thoughtcrime.securesms/u0a83 for activity org.thoughtcrime.securesms/.RoutingActivity
01-09 13:59:30.829: V/WindowManager(525): Adding window Window{22ae25b7 u0 org.thoughtcrime.securesms/org.thoughtcrime.securesms.RoutingActivity} at 2 of 5 (before Window{1a727cc7 u0 Starting org.thoughtcrime.securesms})
01-09 13:59:30.862: W/KeyCachingService(4504): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
01-09 13:59:31.318: W/JobConsumer(4504): 	at org.thoughtcrime.securesms.util.BitmapUtil.createScaledBitmapInto(BitmapUtil.java:104)
01-09 13:59:31.318: W/JobConsumer(4504): 	at org.thoughtcrime.securesms.util.BitmapUtil.createScaledBitmap(BitmapUtil.java:80)
01-09 13:59:31.318: W/JobConsumer(4504): 	at org.thoughtcrime.securesms.util.BitmapUtil.createScaledBytes(BitmapUtil.java:49)
01-09 13:59:31.318: W/JobConsumer(4504): 	at org.thoughtcrime.securesms.mms.MediaConstraints.getResizedMedia(MediaConstraints.java:74)
01-09 13:59:31.318: W/JobConsumer(4504): 	at org.thoughtcrime.securesms.jobs.SendJob.scaleAttachments(SendJob.java:69)
01-09 13:59:31.318: W/JobConsumer(4504): 	at org.thoughtcrime.securesms.jobs.PushMediaSendJob.deliver(PushMediaSendJob.java:119)
01-09 13:59:31.318: W/JobConsumer(4504): 	at org.thoughtcrime.securesms.jobs.PushMediaSendJob.onSend(PushMediaSendJob.java:69)
01-09 13:59:31.318: W/JobConsumer(4504): 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:43)
01-09 13:59:31.318: W/JobConsumer(4504): 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
01-09 13:59:31.319: E/AndroidRuntime(4504): Process: org.thoughtcrime.securesms, PID: 4504
01-09 13:59:31.319: E/AndroidRuntime(4504): 	at org.thoughtcrime.securesms.util.BitmapUtil.createScaledBitmapInto(BitmapUtil.java:104)
01-09 13:59:31.319: E/AndroidRuntime(4504): 	at org.thoughtcrime.securesms.util.BitmapUtil.createScaledBitmap(BitmapUtil.java:80)
01-09 13:59:31.319: E/AndroidRuntime(4504): 	at org.thoughtcrime.securesms.util.BitmapUtil.createScaledBytes(BitmapUtil.java:49)
01-09 13:59:31.319: E/AndroidRuntime(4504): 	at org.thoughtcrime.securesms.mms.MediaConstraints.getResizedMedia(MediaConstraints.java:74)
01-09 13:59:31.319: E/AndroidRuntime(4504): 	at org.thoughtcrime.securesms.jobs.SendJob.scaleAttachments(SendJob.java:69)
01-09 13:59:31.319: E/AndroidRuntime(4504): 	at org.thoughtcrime.securesms.jobs.PushMediaSendJob.deliver(PushMediaSendJob.java:119)
01-09 13:59:31.319: E/AndroidRuntime(4504): 	at org.thoughtcrime.securesms.jobs.PushMediaSendJob.onSend(PushMediaSendJob.java:69)
01-09 13:59:31.319: E/AndroidRuntime(4504): 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:43)
01-09 13:59:31.319: E/AndroidRuntime(4504): 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
01-09 13:59:31.320: W/ActivityManager(525):   Force finishing activity 1 org.thoughtcrime.securesms/.RoutingActivity
01-09 13:59:31.628: I/WindowManager(525): Screenshot max retries 4 of Token{224f02cf ActivityRecord{6cec72e u0 org.thoughtcrime.securesms/.RoutingActivity t7081 f}} appWin=Window{1a727cc7 u0 Starting org.thoughtcrime.securesms} drawState=4
01-09 13:59:31.644: W/BroadcastQueue(525): Skipping deliver [background] BroadcastRecord{23a5fb54 u-1 android.net.conn.CONNECTIVITY_CHANGE} to ReceiverList{169b8766 4504 org.thoughtcrime.securesms/10083/u0 remote:19d4b3c1}: process crashing
01-09 13:59:31.657: W/PackageManager(746): Failure retrieving resources for org.thoughtcrime.securesms: Resource ID #0x0
01-09 13:59:31.692: W/KeyCachingService(4504): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
01-09 13:59:32.941: I/ActivityManager(525): Process org.thoughtcrime.securesms (pid 4504) has died
01-09 13:59:32.941: W/ActivityManager(525): Scheduling restart of crashed service org.thoughtcrime.securesms/.service.KeyCachingService in 1000ms
01-09 13:59:32.941: W/ActivityManager(525): Scheduling restart of crashed service org.thoughtcrime.securesms/.service.MessageRetrievalService in 1000ms
01-09 13:59:34.006: I/ActivityManager(525): Start proc 4554:org.thoughtcrime.securesms/u0a83 for service org.thoughtcrime.securesms/.service.MessageRetrievalService
01-09 13:59:34.753: W/JobConsumer(4554): 	at org.thoughtcrime.securesms.util.BitmapUtil.createScaledBitmapInto(BitmapUtil.java:104)
01-09 13:59:34.753: W/JobConsumer(4554): 	at org.thoughtcrime.securesms.util.BitmapUtil.createScaledBitmap(BitmapUtil.java:80)
01-09 13:59:34.753: W/JobConsumer(4554): 	at org.thoughtcrime.securesms.util.BitmapUtil.createScaledBytes(BitmapUtil.java:49)
01-09 13:59:34.753: W/JobConsumer(4554): 	at org.thoughtcrime.securesms.mms.MediaConstraints.getResizedMedia(MediaConstraints.java:74)
01-09 13:59:34.753: W/JobConsumer(4554): 	at org.thoughtcrime.securesms.jobs.SendJob.scaleAttachments(SendJob.java:69)
01-09 13:59:34.753: W/JobConsumer(4554): 	at org.thoughtcrime.securesms.jobs.PushMediaSendJob.deliver(PushMediaSendJob.java:119)
01-09 13:59:34.753: W/JobConsumer(4554): 	at org.thoughtcrime.securesms.jobs.PushMediaSendJob.onSend(PushMediaSendJob.java:69)
01-09 13:59:34.753: W/JobConsumer(4554): 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:43)
01-09 13:59:34.753: W/JobConsumer(4554): 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
01-09 13:59:34.753: E/AndroidRuntime(4554): Process: org.thoughtcrime.securesms, PID: 4554
01-09 13:59:34.753: E/AndroidRuntime(4554): 	at org.thoughtcrime.securesms.util.BitmapUtil.createScaledBitmapInto(BitmapUtil.java:104)
01-09 13:59:34.753: E/AndroidRuntime(4554): 	at org.thoughtcrime.securesms.util.BitmapUtil.createScaledBitmap(BitmapUtil.java:80)
01-09 13:59:34.753: E/AndroidRuntime(4554): 	at org.thoughtcrime.securesms.util.BitmapUtil.createScaledBytes(BitmapUtil.java:49)
01-09 13:59:34.753: E/AndroidRuntime(4554): 	at org.thoughtcrime.securesms.mms.MediaConstraints.getResizedMedia(MediaConstraints.java:74)
01-09 13:59:34.753: E/AndroidRuntime(4554): 	at org.thoughtcrime.securesms.jobs.SendJob.scaleAttachments(SendJob.java:69)
01-09 13:59:34.753: E/AndroidRuntime(4554): 	at org.thoughtcrime.securesms.jobs.PushMediaSendJob.deliver(PushMediaSendJob.java:119)
01-09 13:59:34.753: E/AndroidRuntime(4554): 	at org.thoughtcrime.securesms.jobs.PushMediaSendJob.onSend(PushMediaSendJob.java:69)
01-09 13:59:34.753: E/AndroidRuntime(4554): 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:43)
01-09 13:59:34.753: E/AndroidRuntime(4554): 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
01-09 13:59:36.414: I/ActivityManager(525): Process org.thoughtcrime.securesms (pid 4554) has died
01-09 13:59:36.414: W/ActivityManager(525): Scheduling restart of crashed service org.thoughtcrime.securesms/.service.KeyCachingService in 1000ms
01-09 13:59:36.415: W/ActivityManager(525): Service crashed 2 times, stopping: ServiceRecord{4a0f6db u0 org.thoughtcrime.securesms/.service.MessageRetrievalService}
```

**Comment by haffenloher** [comment]
As a workaround you can open the app in flight mode and delete the problematic message. That should work

**Comment by exploide** [comment]
Ah, good idea. That worked, thanks.
