### ISSUE TITLE
can't send sms

### ISSUE THREAD

**Issue by smidm** [WhisperSystems/Signal-Android#5112]
After replying to non-signal contact I sometimes get "SMS not delivered" and resend does nothing.

https://gist.github.com/anonymous/8bb4f67f7b13e8a481da

**Comment by agrajaghh** [comment]
```
W/SmsSendJob( 9133): org.thoughtcrime.securesms.transport.UndeliverableMessageException: Trying to send a secure SMS?
W/SmsSendJob( 9133): 	at org.thoughtcrime.securesms.jobs.SmsSendJob.deliver(SmsSendJob.java:82)
W/SmsSendJob( 9133): 	at org.thoughtcrime.securesms.jobs.SmsSendJob.onSend(SmsSendJob.java:55)
W/SmsSendJob( 9133): 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:43)
W/SmsSendJob( 9133): 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
W/SmsSendJob( 9133): 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
W/SmsSendJob( 9133): 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
```

related to #4765 #3096 (or dupe?)

**Comment by moxie0** [comment]
dupe =(
