### ISSUE TITLE
"Bad encrypted message" if ending a session arrives too late

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/Signal-Android#5119]
Android seems to get confused if it receives end secure session message later than the messages sent after it.

#### Steps
1. In a conversation with an Android
1. Android turns on airplaine mode
1. I end the session
1. I send three messages
1. Android turns off airplaine mode
1. Android receives two of my messages
1. Android receives my end session message
1. Android receives my third message and it is a _Bad encrypted message..._
1. Android sees all subsequent messages from me as _Bad encrypted message..._
1. If Android sends me a message everything works again

![end session bad encrypted message](https://cloud.githubusercontent.com/assets/174176/12532857/3b40de20-c227-11e5-893a-58cb4eb97bdc.png)

The screen shots and logs are from Desktop 0.1.9 and Android 3.9.1
But I'm able to reproduce this just between two Androids as well.

Desktop log: https://gist.github.com/anonymous/ca35e4cf3dee37325a7e
Android spammy log: https://gist.github.com/anonymous/72461983b75eca46950a
```
W/PushDecryptJob(10541): org.whispersystems.libaxolotl.InvalidKeyIdException: java.io.FileNotFoundException: /data/data/org.thoughtcrime.securesms/files/prekeys/9348061: open failed: ENOENT (No such file or directory)
W/PushDecryptJob(10541): 	at org.thoughtcrime.securesms.crypto.storage.TextSecurePreKeyStore.loadPreKey(TextSecurePreKeyStore.java:57)
W/PushDecryptJob(10541): 	at org.thoughtcrime.securesms.crypto.storage.TextSecureAxolotlStore.loadPreKey(TextSecureAxolotlStore.java:56)
W/PushDecryptJob(10541): 	at org.whispersystems.libaxolotl.SessionBuilder.processV3(SessionBuilder.java:140)
W/PushDecryptJob(10541): 	at org.whispersystems.libaxolotl.SessionBuilder.process(SessionBuilder.java:112)
W/PushDecryptJob(10541): 	at org.whispersystems.libaxolotl.SessionCipher.decrypt(SessionCipher.java:183)
W/PushDecryptJob(10541): 	at org.whispersystems.libaxolotl.SessionCipher.decrypt(SessionCipher.java:153)
W/PushDecryptJob(10541): 	at org.whispersystems.textsecure.api.crypto.TextSecureCipher.decrypt(TextSecureCipher.java:148)
W/PushDecryptJob(10541): 	at org.whispersystems.textsecure.api.crypto.TextSecureCipher.decrypt(TextSecureCipher.java:119)
W/PushDecryptJob(10541): 	at org.thoughtcrime.securesms.jobs.PushDecryptJob.handleMessage(PushDecryptJob.java:135)
W/PushDecryptJob(10541): 	at org.thoughtcrime.securesms.jobs.PushDecryptJob.onRun(PushDecryptJob.java:115)
W/PushDecryptJob(10541): 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
W/PushDecryptJob(10541): 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
W/PushDecryptJob(10541): Caused by: java.io.FileNotFoundException: /data/data/org.thoughtcrime.securesms/files/prekeys/9348061: open failed: ENOENT (No such file or directory)
W/PushDecryptJob(10541): 	at libcore.io.IoBridge.open(IoBridge.java:406)
W/PushDecryptJob(10541): 	at java.io.FileInputStream.<init>(FileInputStream.java:78)
W/PushDecryptJob(10541): 	at org.thoughtcrime.securesms.crypto.storage.TextSecurePreKeyStore.loadSerializedRecord(TextSecurePreKeyStore.java:172)
W/PushDecryptJob(10541): 	at org.thoughtcrime.securesms.crypto.storage.TextSecurePreKeyStore.loadPreKey(TextSecurePreKeyStore.java:54)
W/PushDecryptJob(10541): 	... 11 more
W/PushDecryptJob(10541): Caused by: libcore.io.ErrnoException: open failed: ENOENT (No such file or directory)
W/PushDecryptJob(10541): 	at libcore.io.Posix.open(Native Method)
W/PushDecryptJob(10541): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
W/PushDecryptJob(10541): 	at libcore.io.IoBridge.open(IoBridge.java:390)
W/PushDecryptJob(10541): 	... 14 more
```

**Comment by 2-4601** [comment]
I guess this is a stupid edge case and will be taken care of when the manual reset session option is not needed any more.
Closing.
