### ISSUE TITLE
Unable to download MMS

### ISSUE THREAD

**Issue by bmkilpat** [WhisperSystems/Signal-Android#5190]
I am currently unable to send or receive MMS messages via signal. I have posted the relevant logs below:

```
Device : motorola Moto G (cm_falcon)
Android : 6.0.1 (e55e8890da, cm_falcon-userdebug 6.0.1 MMB29U e55e8890da test-keys)
Memory : 28M (31.74% free, 96M max)
Memclass: 96
OS Host : cyanogenmod
App : Signal 3.10.0
... [I've omitted everything before 3:32 pm, which was when I tried to download an MMS as a test.]

02-07 15:32:15.325 17225 17225 W PassphraseRequiredActionBarActivity: onDestroy()
02-07 15:32:15.411 17225 17225 W PassphraseRequiredActionBarActivity: onResume()
02-07 15:32:15.697 17225 17225 W KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
02-07 15:32:15.697 17225 17225 W KeyCachingService: Incrementing activity count...
02-07 15:32:15.698 17225 17225 W MessageRetrievalService: Active Count: 1
02-07 15:32:15.702 17225 17245 W MessageRetrievalService: Network requirement: true, active activities: 1, push pending: 0
02-07 15:32:15.703 17225 17245 W MessageRetrievalService: Making websocket connection....
02-07 15:32:15.705 17225 17245 W WebSocketConnection: WSC connect()...
02-07 15:32:15.705 17225 17245 W OkHttpClientWrapper: Connecting to: wss://textsecure-service.whispersystems.org/v1/websocket/?login=%s&password=%s
02-07 15:32:15.708 17225 17245 W MessageRetrievalService: Network requirement: true, active activities: 1, push pending: 0
02-07 15:32:15.708 17225 17245 W MessageRetrievalService: Reading message...
02-07 15:32:18.444 17225 17225 W PassphraseRequiredActionBarActivity: onPause()
02-07 15:32:18.454 17225 17225 W KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
02-07 15:32:18.454 17225 17225 W KeyCachingService: Decrementing activity count...
02-07 15:32:18.454 17225 17225 W MessageRetrievalService: Active Count: 0
02-07 15:32:18.485 17225 17225 W PassphraseRequiredActionBarActivity: onCreate(null)
02-07 15:32:18.488 17225 17225 W ExperienceUpgradeActivity: getExperienceUpgrade(181)
02-07 15:32:18.489 17225 17225 W PassphraseRequiredActionBarActivity: routeApplicationState(), state: 0
02-07 15:32:18.508 17225 17225 W PassphraseRequiredActionBarActivity: initializeClearKeyReceiver()
02-07 15:32:18.509 17225 17225 W ConversationActivity: onCreate()
02-07 15:32:18.558 17225 17225 W QuickAttachmentDrawer: updateControlsView()
02-07 15:32:18.689 17225 17225 W PassphraseRequiredActionBarActivity: onResume()
02-07 15:32:18.694 17225 19441 W MmsSmsDatabase: Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type, attachment_id, unique_id, mid, data_size, _data, ct, cl, cd, name, pending_push FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type, NULL AS unique_id, NULL AS mid, NULL AS data_size, NULL AS _data, NULL AS ct, NULL AS cl, NULL AS cd, NULL AS name, NULL AS pending_push FROM sms WHERE (thread_id = 34) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'MMS::' || mms._id || '::' || date AS unique_row_id, part._id AS attachment_id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type, unique_id, NULL AS mid, data_size, NULL AS _data, ct, cl, cd, name, pending_push FROM mms LEFT OUTER JOIN part ON part._id = (SELECT part._id FROM part WHERE part.mid = mms._id LIMIT 1) WHERE (thread_id = 34) ORDER BY date_received DESC LIMIT 500)
02-07 15:32:18.722 17225 17225 W KeyboardAwareLinearLayout: rotation changed
02-07 15:32:18.722 17225 17225 W KeyboardAwareLinearLayout: onKeyboardClose()
02-07 15:32:18.737 17225 17225 W CameraView: skipping layout due to zero-width/height preview size
02-07 15:32:18.740 17225 17225 W KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
02-07 15:32:18.740 17225 17225 W KeyCachingService: Incrementing activity count...
02-07 15:32:18.740 17225 17225 W MessageRetrievalService: Active Count: 1
02-07 15:32:18.758 17225 19560 W MmsSmsDatabase: Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type, attachment_id, unique_id, mid, data_size, _data, ct, cl, cd, name, pending_push FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type, NULL AS unique_id, NULL AS mid, NULL AS data_size, NULL AS _data, NULL AS ct, NULL AS cl, NULL AS cd, NULL AS name, NULL AS pending_push FROM sms WHERE (read = 0) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'MMS::' || mms._id || '::' || date AS unique_row_id, part._id AS attachment_id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type, unique_id, NULL AS mid, data_size, NULL AS _data, ct, cl, cd, name, pending_push FROM mms LEFT OUTER JOIN part ON part._id = (SELECT part._id FROM part WHERE part.mid = mms._id LIMIT 1) WHERE (read = 0) ORDER BY date_received ASC)
02-07 15:32:18.862 17225 17225 W PhoneNumberFormatter: Got local CC: US
02-07 15:32:18.887 17225 21888 W WebSocketConnection: onConnected()
02-07 15:32:18.962 17225 17225 W PhoneNumberFormatter: Got local CC: US
02-07 15:32:19.005 17225 17225 W PhoneNumberFormatter: Got local CC: US
02-07 15:32:19.042 17225 17225 W PhoneNumberFormatter: Got local CC: US
02-07 15:32:19.079 17225 17225 W PhoneNumberFormatter: Got local CC: US
02-07 15:32:19.124 17225 18881 D OpenGLRenderer: endAllStagingAnimators on 0xb8becf30 (RippleDrawable) with handle 0xb8f02e78
02-07 15:32:21.309 17225 17225 W ConversationItem: Content location: http://sobmm.myboostmobile.com/ammsc/?MUSASm8X615043589839
02-07 15:32:21.413 17225 17239 W MmsDownloadJob: Downloading mms at sobmm.myboostmobile.com
02-07 15:32:21.413 17225 19566 W MmsSmsDatabase: Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type, attachment_id, unique_id, mid, data_size, _data, ct, cl, cd, name, pending_push FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type, NULL AS unique_id, NULL AS mid, NULL AS data_size, NULL AS _data, NULL AS ct, NULL AS cl, NULL AS cd, NULL AS name, NULL AS pending_push FROM sms WHERE (thread_id = 34) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'MMS::' || mms._id || '::' || date AS unique_row_id, part._id AS attachment_id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type, unique_id, NULL AS mid, data_size, NULL AS _data, ct, cl, cd, name, pending_push FROM mms LEFT OUTER JOIN part ON part._id = (SELECT part._id FROM part WHERE part.mid = mms._id LIMIT 1) WHERE (thread_id = 34) ORDER BY date_received DESC LIMIT 500)
02-07 15:32:21.415 17225 17239 W CompatMmsConnection: Receiving via legacy connection
02-07 15:32:21.431 17225 17239 W TelephonyUtil: Choosing MCC+MNC info from current context's Configuration
02-07 15:32:21.432 17225 17239 W ApnDatabase: Querying table for MCC+MNC 3100 without APN name
02-07 15:32:21.437 17225 17225 W PhoneNumberFormatter: Got local CC: US
02-07 15:32:21.439 17225 17239 W ApnDatabase: No matching APNs found, returning null
02-07 15:32:21.445 17225 17239 W CompatMmsConnection: Falling back to try receiving via Lollipop API
02-07 15:32:21.450 17225 17239 W IncomingLollipopMmsConnection: downloading multimedia from http://sobmm.myboostmobile.com/ammsc/?MUSASm8X615043589839 to content://org.thoughtcrime.provider.securesms.mms/mms/1454880741449
02-07 15:32:21.460 17225 17225 W PhoneNumberFormatter: Got local CC: US
02-07 15:32:21.481 17225 17225 W PhoneNumberFormatter: Got local CC: US
02-07 15:32:21.500 17225 17225 W PhoneNumberFormatter: Got local CC: US
02-07 15:32:21.524 17225 17225 W PhoneNumberFormatter: Got local CC: US
02-07 15:32:23.247 17225 17225 W LollipopMmsConnection: onReceive()
02-07 15:32:23.247 17225 17225 W IncomingLollipopMmsConnection: HTTP status: -1
02-07 15:32:23.248 17225 17225 W IncomingLollipopMmsConnection: code: 2, result string: null
02-07 15:32:23.250 17225 17239 W MmsBodyProvider: openFile(content://org.thoughtcrime.provider.securesms.mms/mms/1454880741449, r)
02-07 15:32:23.250 17225 17239 W MmsBodyProvider: Fetching message body for a single row...
02-07 15:32:23.251 17225 17239 W MmsBodyProvider: returning file /data/user/0/org.thoughtcrime.securesms/cache/1454880741449.mmsbody
02-07 15:32:23.259 17225 17239 W IncomingLollipopMmsConnection: java.io.FileNotFoundException: No such file or directory
02-07 15:32:23.259 17225 17239 W IncomingLollipopMmsConnection: at android.os.Parcel.openFileDescriptor(Native Method)
02-07 15:32:23.259 17225 17239 W IncomingLollipopMmsConnection: at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:270)
02-07 15:32:23.259 17225 17239 W IncomingLollipopMmsConnection: at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:200)
02-07 15:32:23.259 17225 17239 W IncomingLollipopMmsConnection: at org.thoughtcrime.securesms.providers.MmsBodyProvider.openFile(MmsBodyProvider.java:77)
02-07 15:32:23.259 17225 17239 W IncomingLollipopMmsConnection: at android.content.ContentProvider.openAssetFile(ContentProvider.java:1374)
02-07 15:32:23.259 17225 17239 W IncomingLollipopMmsConnection: at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:1554)
02-07 15:32:23.259 17225 17239 W IncomingLollipopMmsConnection: at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:1620)
02-07 15:32:23.259 17225 17239 W IncomingLollipopMmsConnection: at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:419)
02-07 15:32:23.259 17225 17239 W IncomingLollipopMmsConnection: at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1107)
02-07 15:32:23.259 17225 17239 W IncomingLollipopMmsConnection: at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:944)
02-07 15:32:23.259 17225 17239 W IncomingLollipopMmsConnection: at android.content.ContentResolver.openInputStream(ContentResolver.java:664)
02-07 15:32:23.259 17225 17239 W IncomingLollipopMmsConnection: at org.thoughtcrime.securesms.providers.MmsBodyProvider$Pointer.getInputStream(MmsBodyProvider.java:133)
02-07 15:32:23.259 17225 17239 W IncomingLollipopMmsConnection: at org.thoughtcrime.securesms.mms.IncomingLollipopMmsConnection.retrieve(IncomingLollipopMmsConnection.java:78)
02-07 15:32:23.259 17225 17239 W IncomingLollipopMmsConnection: at org.thoughtcrime.securesms.mms.CompatMmsConnection.retrieve(CompatMmsConnection.java:57)
02-07 15:32:23.259 17225 17239 W IncomingLollipopMmsConnection: at org.thoughtcrime.securesms.jobs.MmsDownloadJob.onRun(MmsDownloadJob.java:98)
02-07 15:32:23.259 17225 17239 W IncomingLollipopMmsConnection: at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
02-07 15:32:23.259 17225 17239 W IncomingLollipopMmsConnection: at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
02-07 15:32:23.259 17225 17239 W IncomingLollipopMmsConnection: at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
02-07 15:32:23.262 17225 17239 W MmsDownloadJob: ws.com.google.android.mms.MmsException: java.io.FileNotFoundException: No such file or directory
02-07 15:32:23.262 17225 17239 W MmsDownloadJob: at org.thoughtcrime.securesms.mms.IncomingLollipopMmsConnection.retrieve(IncomingLollipopMmsConnection.java:86)
02-07 15:32:23.262 17225 17239 W MmsDownloadJob: at org.thoughtcrime.securesms.mms.CompatMmsConnection.retrieve(CompatMmsConnection.java:57)
02-07 15:32:23.262 17225 17239 W MmsDownloadJob: at org.thoughtcrime.securesms.jobs.MmsDownloadJob.onRun(MmsDownloadJob.java:98)
02-07 15:32:23.262 17225 17239 W MmsDownloadJob: at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
02-07 15:32:23.262 17225 17239 W MmsDownloadJob: at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
02-07 15:32:23.262 17225 17239 W MmsDownloadJob: at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
02-07 15:32:23.262 17225 17239 W MmsDownloadJob: Caused by: java.io.FileNotFoundException: No such file or directory
02-07 15:32:23.262 17225 17239 W MmsDownloadJob: at android.os.Parcel.openFileDescriptor(Native Method)
02-07 15:32:23.262 17225 17239 W MmsDownloadJob: at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:270)
02-07 15:32:23.262 17225 17239 W MmsDownloadJob: at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:200)
02-07 15:32:23.262 17225 17239 W MmsDownloadJob: at org.thoughtcrime.securesms.providers.MmsBodyProvider.openFile(MmsBodyProvider.java:77)
02-07 15:32:23.262 17225 17239 W MmsDownloadJob: at android.content.ContentProvider.openAssetFile(ContentProvider.java:1374)
02-07 15:32:23.262 17225 17239 W MmsDownloadJob: at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:1554)
02-07 15:32:23.262 17225 17239 W MmsDownloadJob: at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:1620)
02-07 15:32:23.262 17225 17239 W MmsDownloadJob: at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:419)
02-07 15:32:23.262 17225 17239 W MmsDownloadJob: at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1107)
02-07 15:32:23.262 17225 17239 W MmsDownloadJob: at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:944)
02-07 15:32:23.262 17225 17239 W MmsDownloadJob: at android.content.ContentResolver.openInputStream(ContentResolver.java:664)
02-07 15:32:23.262 17225 17239 W MmsDownloadJob: at org.thoughtcrime.securesms.providers.MmsBodyProvider$Pointer.getInputStream(MmsBodyProvider.java:133)
02-07 15:32:23.262 17225 17239 W MmsDownloadJob: at org.thoughtcrime.securesms.mms.IncomingLollipopMmsConnection.retrieve(IncomingLollipopMmsConnection.java:78)
02-07 15:32:23.262 17225 17239 W MmsDownloadJob: ... 5 more
02-07 15:32:23.283 17225 18876 W MmsSmsDatabase: Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type, attachment_id, unique_id, mid, data_size, _data, ct, cl, cd, name, pending_push FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type, NULL AS unique_id, NULL AS mid, NULL AS data_size, NULL AS _data, NULL AS ct, NULL AS cl, NULL AS cd, NULL AS name, NULL AS pending_push FROM sms WHERE (thread_id = 34) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'MMS::' || mms._id || '::' || date AS unique_row_id, part._id AS attachment_id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type, unique_id, NULL AS mid, data_size, NULL AS _data, ct, cl, cd, name, pending_push FROM mms LEFT OUTER JOIN part ON part._id = (SELECT part._id FROM part WHERE part.mid = mms._id LIMIT 1) WHERE (thread_id = 34) ORDER BY date_received DESC LIMIT 500)
02-07 15:32:23.301 17225 17225 W PhoneNumberFormatter: Got local CC: US
02-07 15:32:23.319 17225 17225 W PhoneNumberFormatter: Got local CC: US
02-07 15:32:23.335 17225 17225 W PhoneNumberFormatter: Got local CC: US
02-07 15:32:23.351 17225 17225 W PhoneNumberFormatter: Got local CC: US
02-07 15:32:23.368 17225 17225 W PhoneNumberFormatter: Got local CC: US
02-07 15:32:24.562 17225 17225 W ConversationActivity: onBackPressed()
02-07 15:32:24.574 17225 17225 W PassphraseRequiredActionBarActivity: onPause()
02-07 15:32:24.581 17225 17225 W KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
02-07 15:32:24.582 17225 17225 W KeyCachingService: Decrementing activity count...
02-07 15:32:24.582 17225 17225 W MessageRetrievalService: Active Count: 0
02-07 15:32:24.583 17225 17225 W PassphraseRequiredActionBarActivity: onResume()
02-07 15:32:24.742 17225 17225 W KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
02-07 15:32:24.742 17225 17225 W KeyCachingService: Incrementing activity count...
02-07 15:32:24.742 17225 17225 W MessageRetrievalService: Active Count: 1
02-07 15:32:24.968 17225 17225 W PassphraseRequiredActionBarActivity: onDestroy()
02-07 15:32:24.975 17225 19564 W MmsSmsDatabase: Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type, attachment_id, unique_id, mid, data_size, _data, ct, cl, cd, name, pending_push FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type, NULL AS unique_id, NULL AS mid, NULL AS data_size, NULL AS _data, NULL AS ct, NULL AS cl, NULL AS cd, NULL AS name, NULL AS pending_push FROM sms WHERE (thread_id = 34) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'MMS::' || mms._id || '::' || date AS unique_row_id, part._id AS attachment_id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type, unique_id, NULL AS mid, data_size, NULL AS _data, ct, cl, cd, name, pending_push FROM mms LEFT OUTER JOIN part ON part._id = (SELECT part._id FROM part WHERE part.mid = mms._id LIMIT 1) WHERE (thread_id = 34) ORDER BY date_received DESC LIMIT 1)
02-07 15:32:24.986 17225 19564 W PhoneNumberFormatter: Got local CC: US
02-07 15:32:26.960 17225 17225 W PassphraseRequiredActionBarActivity: onPause()
02-07 15:32:26.972 17225 17225 W KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
02-07 15:32:26.972 17225 17225 W KeyCachingService: Decrementing activity count...
02-07 15:32:26.972 17225 17225 W MessageRetrievalService: Active Count: 0
02-07 15:32:26.987 17225 17225 W PassphraseRequiredActionBarActivity: onCreate(null)
02-07 15:32:26.990 17225 17225 W ExperienceUpgradeActivity: getExperienceUpgrade(181)
02-07 15:32:26.990 17225 17225 W PassphraseRequiredActionBarActivity: routeApplicationState(), state: 0
02-07 15:32:27.004 17225 17225 W PassphraseRequiredActionBarActivity: initializeClearKeyReceiver()
02-07 15:32:27.052 17225 17225 W PassphraseRequiredActionBarActivity: onResume()
02-07 15:32:27.372 17225 17225 W KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
02-07 15:32:27.372 17225 17225 W KeyCachingService: Incrementing activity count...
02-07 15:32:27.379 17225 17225 W MessageRetrievalService: Active Count: 1
02-07 15:32:27.419 17225 18881 D OpenGLRenderer: endAllStagingAnimators on 0xb96c6ab8 (ListPopupWindow$DropDownListView) with handle 0xb9658cb8
02-07 15:32:27.471 17225 17235 I art : Background sticky concurrent mark sweep GC freed 43457(2MB) AllocSpace objects, 1(20KB) LOS objects, 14% free, 18MB/22MB, paused 6.284ms total 283.453ms
02-07 15:32:29.988 17225 17225 W PassphraseRequiredActionBarActivity: onPause()
02-07 15:32:30.001 17225 17225 W KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
02-07 15:32:30.001 17225 17225 W KeyCachingService: Decrementing activity count...
02-07 15:32:30.002 17225 17225 W MessageRetrievalService: Active Count: 0
02-07 15:32:30.233 17225 18881 D OpenGLRenderer: endAllStagingAnimators on 0xb9401a80 (ListView) with handle 0xb8b79270
```

**Comment by thewholelifetolearn** [comment]
Hi!

I have a similar problem. Since the last update of Signal, I can't download MMS. I need to configure the MMS settings for Signal but it is already done for the phone. It was working fine until now.

You can find the log file at https://gist.github.com/anonymous/0ce1fce2021aad9b6b9b

**Comment by moxie0** [comment]
@bmkilpat From your log, the system is returning "MMS_ERROR_INVALID_APN," which suggests you don't have your APN information configured correctly in your system settings.

**Comment by moxie0** [comment]
@thewholelifetolearn You're running pre-lollipop, so there's no way for the app to use the system APN settings, which is why you have to configure your APN in the app itself.

**Comment by thewholelifetolearn** [comment]
Ok. Thanks for the answer @moxie0 but how did it manage to work before? Downloading MMS worked before!
