### ISSUE TITLE
3.14 crashes during call

### ISSUE THREAD

**Issue by digititus** [WhisperSystems/Signal-Android#5337]
When I make a call in Signal with v3.14, the app crashes and the call fails. (Unfortunately etc.)
Android 5.1.1, Experia Z3 (Cyanogenmod 12.1)
I have tried the following:
1. Reboot
2. Uninstall, re-install 3.14
Same problem.

Removing 3.14 and replacing with 3.13.1 fixes the problem.

I would give logcat, but this is my DD and I have Signal working again.

**Comment by 2-4601** [comment]
Nexus 4, stock 5.1.1, Signal 3.14.0
https://gist.github.com/anonymous/39efaf8a894af94c2c05
```
E/AndroidRuntime( 8510): FATAL EXCEPTION: InitiatingCallManager Thread
E/AndroidRuntime( 8510): Process: org.thoughtcrime.securesms, PID: 8510
E/AndroidRuntime( 8510): java.lang.AssertionError: java.security.NoSuchAlgorithmException: KeyPairGenerator ECDH implementation not found
E/AndroidRuntime( 8510): 	at org.thoughtcrime.redphone.crypto.zrtp.ZRTPSocket.initializeEC25Keys(ZRTPSocket.java:257)
E/AndroidRuntime( 8510): 	at org.thoughtcrime.redphone.crypto.zrtp.ZRTPSocket.<init>(ZRTPSocket.java:106)
E/AndroidRuntime( 8510): 	at org.thoughtcrime.redphone.crypto.zrtp.ZRTPInitiatorSocket.<init>(ZRTPInitiatorSocket.java:56)
E/AndroidRuntime( 8510): 	at org.thoughtcrime.redphone.call.InitiatingCallManager.run(InitiatingCallManager.java:88)
E/AndroidRuntime( 8510): Caused by: java.security.NoSuchAlgorithmException: KeyPairGenerator ECDH implementation not found
E/AndroidRuntime( 8510): 	at org.apache.harmony.security.fortress.Engine.notFound(Engine.java:190)
E/AndroidRuntime( 8510): 	at org.apache.harmony.security.fortress.Engine.getInstance(Engine.java:183)
E/AndroidRuntime( 8510): 	at java.security.KeyPairGenerator.getInstance(KeyPairGenerator.java:149)
E/AndroidRuntime( 8510): 	at java.security.KeyPairGenerator.getInstance(KeyPairGenerator.java:122)
E/AndroidRuntime( 8510): 	at org.thoughtcrime.redphone.crypto.zrtp.ZRTPSocket.initializeEC25Keys(ZRTPSocket.java:249)
E/AndroidRuntime( 8510): 	... 3 more
```

**Comment by Dyras** [comment]
Same on Moto G 2015
https://gist.github.com/anonymous/62b576ad74d63028c40a

**Comment by agrajaghh** [comment]
is this caused by the proguard fix? https://github.com/WhisperSystems/Signal-Android/commit/9aec80beda6b63a317a90dd33242bd066f0ddaa1

**Comment by 2-4601** [comment]
It sure is. Reverting that commit makes it not crash for me.

**Comment by peterpanondrugs** [comment]
https://gist.github.com/b3020da3f1140863fe69

**Comment by thrillfall** [comment]
Same on Moto E 2015 (LTE) CM-12.1
