### ISSUE TITLE
Signal 3.18.0beta crashes at start

### ISSUE THREAD

**Issue by bungabunga** [WhisperSystems/Signal-Android#5656]
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal 3.18.0beta crashes at start.

### Steps to reproduce
- upgrade Signal from 3.17.0 to 3.18.0 beta via Google Play Store
- try to open it

**Signal crashes every time:**

### Device info
**Device: Sony Xperia Z3 compact**
**Android version: 6.0.1**
**Signal version: 3.18.0beta**

### Link to debug log
Can't send a debug log via Signal because I can not open it. Sent log via Google Play Store.

**Comment by cascheberg** [comment]
@bungabunga Do you have archived conversations and a short list of conversations?

@moxie0 Signal 3.18.0 crashes when I have archived messages and try to scroll to the bottom of the conversation list.
```
FATAL EXCEPTION: main
Process: org.thoughtcrime.securesms, PID: 18893
java.lang.IllegalArgumentException: column 'expires_in' does not exist
    at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:303)
    at org.thoughtcrime.securesms.database.ThreadDatabase$Reader.getCurrent(ThreadDatabase.java:578)
    at org.thoughtcrime.securesms.ConversationListAdapter.getThreadRecord(ConversationListAdapter.java:169)
    at org.thoughtcrime.securesms.ConversationListAdapter.getItemViewType(ConversationListAdapter.java:159)
    at org.thoughtcrime.securesms.database.CursorRecyclerViewAdapter.getItemViewType(CursorRecyclerViewAdapter.java:158)
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4373)
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4326)
    at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1955)
    at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1364)
    at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1327)
    at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1155)
    at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1012)
    at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:3777)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
    at android.view.Choreographer.doCallbacks(Choreographer.java:580)
    at android.view.Choreographer.doFrame(Choreographer.java:549)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5294)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

**Comment by bungabunga** [comment]
@cascheberg nope.

**Comment by bungabunga** [comment]
@cascheberg actually yes, I do. sorry, I misinterpreted your question.

**Comment by cbarnsdale** [comment]
I'm having the exact same issue. Scrolling to the bottom is an instant crash.

**Comment by bungabunga** [comment]
I can't even open the app.

**Comment by moxie0** [comment]
oh whoops, I think I see what's up
