### ISSUE TITLE
Crash when upgrade SDK

### ISSUE THREAD

**Issue by mdtuyen** [WhisperSystems/Signal-Android#5688]
I update project to:

    compileSdkVersion 24
    buildToolsVersion '24.0.0'

then build and start program:

FATAL EXCEPTION: main
                                                                          Process: org.thoughtcrime.securesms, PID: 6075
                                                                          java.lang.RuntimeException: Unable to start activity ComponentInfo{org.thoughtcrime.securesms/org.thoughtcrime.securesms.ConversationListActivity}: android.view.InflateException: Binary XML file line #31: Error inflating class android.support.design.widget.FloatingActionButton
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2693)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2758)
                                                                              at android.app.ActivityThread.access$900(ActivityThread.java:177)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:145)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5942)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
                                                                           Caused by: android.view.InflateException: Binary XML file line #31: Error inflating class android.support.design.widget.FloatingActionButton
                                                                              at android.view.LayoutInflater.createView(LayoutInflater.java:640)
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750)
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
                                                                              at org.thoughtcrime.securesms.ConversationListFragment.onCreateView(ConversationListFragment.java:108)
                                                                              at android.support.v4.app.Fragment.performCreateView(Fragment.java:2074)
                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1286)
                                                                              at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:758)
                                                                              at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1671)
                                                                              at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
                                                                              at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:619)
                                                                              at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1234)
                                                                              at android.app.Activity.performStart(Activity.java:6328)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2656)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2758) 
                                                                              at android.app.ActivityThread.access$900(ActivityThread.java:177) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:145) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5942) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194) 
                                                                           Caused by: java.lang.reflect.InvocationTargetException
                                                                              at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                              at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                                              at android.view.LayoutInflater.createView(LayoutInflater.java:614)
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750) 
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:511) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:415) 
                                                                              at org.thoughtcrime.securesms.ConversationListFragment.onCreateView(ConversationListFragment.java:108) 
                                                                              at android.support.v4.app.Fragment.performCreateView(Fragment.java:2074) 
                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104) 
                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1286) 
                                                                              at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:758) 
                                                                              at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1671) 
                                                                              at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388) 
                                                                              at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:619) 
                                                                              at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1234) 
                                                                              at android.app.Activity.performStart(Activity.java:6328) 
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2656) 
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2758) 
                                                                              at android.app.ActivityThread.access$900(ActivityThread.java:177) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:145) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5942) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194) 
                                                                           Caused by: java.lang.IllegalArgumentException: You need to use a Theme.AppCompat theme (or descendant) with the design library.
                                                                              at android.support.design.widget.ThemeUtils.checkAppCompatTheme(ThemeUtils.java:36)
                                                                              at android.support.design.widget.FloatingActionButton.<init>(FloatingActionButton.java:153)
                                                                              at android.support.design.widget.FloatingActionButton.<init>(FloatingActionButton.java:147)
                                                                              at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                              at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
                                                                              at android.view.LayoutInflater.createView(LayoutInflater.java:614) 
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750) 
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:511) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:415) 
                                                                              at org.thoughtcrime.securesms.ConversationListFragment.onCreateView(ConversationListFragment.java:108) 
                                                                              at android.support.v4.app.Fragment.performCreateView(Fragment.java:2074) 
                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104) 
                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1286) 
                                                                              at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:758) 
                                                                              at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1671) 
                                                                              at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388) 
                                                                              at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:619) 
                                                                              at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1234) 
                                                                              at android.app.Activity.performStart(Activity.java:6328) 
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2656) 
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2758) 
                                                                              at android.app.ActivityThread.access$900(ActivityThread.java:177) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:145) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5942) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

**Comment by moxie0** [comment]
If you modify the code, you're on your own. This is an issue tracker rather than a discussion forum, please don't expect us to help you debug.
