### ISSUE TITLE
Cannot send a picture from the "Share" button Android Screenshot app

### ISSUE THREAD

**Issue by nagromc** [WhisperSystems/Signal-Android#5752]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Cannot send a picture from the "Share" button Android Screenshot app.

### Steps to reproduce
- Take a screenshot (screenshot 1) with the device (on the Nexus 5X, hold power and volume down buttons). A notification appears with two buttons: "Share" and "Delete" (screenshot 2)
- Tap "Share" (screenshot 2). Android "Share with" screen appears (screenshot 3)
- Tap Signal (screenshot 3). Signal "Share with" screen appears (screenshot 4)
- Tap a contact (screenshot 4). For the purpose of the bug report, I chose my own phone number (ending with "55") but the bug is the same with another contact.

**Actual result:** No thumbnail (screenshot 5). Though, I can share my screenshot by tapping on the paper clip button, then tapping the "Image" button (screenshot 6)
**Expected result:** A thumbnail of the screenshot should appear between the messages and the text field (screenshot 6)

### Screenshots

Screenshot 1: <img src="https://cloud.githubusercontent.com/assets/752443/19152608/1c085882-8bd3-11e6-8302-775224c371e1.png" width="80">
Screenshot 2: <img src="https://cloud.githubusercontent.com/assets/752443/19152614/21036052-8bd3-11e6-9187-1fd34fd87efa.png" width="80">
Screenshot 3: <img src="https://cloud.githubusercontent.com/assets/752443/19152618/234e87f6-8bd3-11e6-9bd7-7e831139cc5c.png" width="80">
Screenshot 4: <img src="https://cloud.githubusercontent.com/assets/752443/19152621/25d02b6a-8bd3-11e6-9c56-bd9cede3ab5d.png" width="80">
Screenshot 5: <img src="https://cloud.githubusercontent.com/assets/752443/19152623/2720dfe6-8bd3-11e6-95e7-d40ed9bac76c.png" width="80">
Screenshot 6: <img src="https://cloud.githubusercontent.com/assets/752443/19152625/286693b4-8bd3-11e6-9dcd-b775d3baa49d.png" width="80">

### Device info
**Device:** LGE Nexus 5X (bullhead)
**Android:** 7.0 (3141966, NRD90R)
**Memory:** 15M (10.24% free, 192M max)
**Memclass:** 192
**OS Host:** vped5.mtv.corp.google.com
**App:** Signal 3.19.1

### Link to debug log

https://gist.github.com/nagromc/728a6310e9c57ca3c10cd5307c2967f1

**Comment by haffenloher** [comment]
```
ShareActivity: java.io.FileNotFoundException: App op not allowed
at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:144)
at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:692)
at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1145)
at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:982)
at android.content.ContentResolver.openInputStream(ContentResolver.java:702)
at org.thoughtcrime.securesms.ShareActivity$ResolveMediaTask.doInBackground(ShareActivity.java:215)
at org.thoughtcrime.securesms.ShareActivity$ResolveMediaTask.doInBackground(ShareActivity.java:196)
at android.os.AsyncTask$2.call(AsyncTask.java:304)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)
```

**Comment by 2-4601** [comment]
Unable to reproduce on Nexus 4, Android 6.0.1, Signal 3.19.1

**Comment by nagromc** [comment]
OK so the bug occurs when the storage permission is disabled. I've just enabled it, and the thumbnail appears as expected.

A [toast](https://developer.android.com/guide/topics/ui/notifiers/toasts.html) may be useful for the user.

**Comment by 2-4601** [comment]
This is tracked at #3983.
