### ISSUE TITLE
Crash when changing the conversation settings of an SMS conversation

### ISSUE THREAD

**Issue by Lehmax** [WhisperSystems/Signal-Android#5760]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal crashes when changing any of the Conversation settings of an SMS conversation. This doesn't happen with encrypted conversations.
### Steps to reproduce
- tap on an SMS conversation
- open the "Conversation settings"
- Change the state of "Mute conversation"
- (this also works with the other settings, but this is the quick way to reproduce it)

**Actual result:** Signal crashes and reopens when I click on Ok.
**Expected result:** The settings should change, Signal should not crash.

### Screenshots

It's hard to take one, because the screen goes black after the crash.

### Device info

**Device:** Moto G 2
**Android version:** 6.0.1
**Signal version:** 3.20.2

### Link to debug log

[log.zip](https://github.com/WhisperSystems/Signal-Android/files/517725/log.zip)

**Comment by 2-4601** [comment]
```
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 4593
E AndroidRuntime: Theme: themes:{}
E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.preference.Preference.onPrepareForRemoval()' on a null object reference
E AndroidRuntime: 	at android.preference.PreferenceGroup.removePreferenceInt(PreferenceGroup.java:188)
E AndroidRuntime: 	at android.preference.PreferenceGroup.removePreference(PreferenceGroup.java:181)
E AndroidRuntime: 	at org.thoughtcrime.securesms.RecipientPreferenceActivity$RecipientPreferenceFragment$2.onSuccess(RecipientPreferenceActivity.java:301)
E AndroidRuntime: 	at org.thoughtcrime.securesms.RecipientPreferenceActivity$RecipientPreferenceFragment$2.onSuccess(RecipientPreferenceActivity.java:294)
E AndroidRuntime: 	at org.thoughtcrime.securesms.util.concurrent.SettableFuture.notifyListener(SettableFuture.java:110)
E AndroidRuntime: 	at org.thoughtcrime.securesms.util.concurrent.SettableFuture.notifyAllListeners(SettableFuture.java:104)
E AndroidRuntime: 	at org.thoughtcrime.securesms.util.concurrent.SettableFuture.set(SettableFuture.java:47)
E AndroidRuntime: 	at org.thoughtcrime.securesms.util.IdentityUtil$1.onPostExecute(IdentityUtil.java:44)
E AndroidRuntime: 	at org.thoughtcrime.securesms.util.IdentityUtil$1.onPostExecute(IdentityUtil.java:28)
E AndroidRuntime: 	at android.os.AsyncTask.finish(AsyncTask.java:651)
E AndroidRuntime: 	at android.os.AsyncTask.-wrap1(AsyncTask.java)
E AndroidRuntime: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5461)
E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
