### ISSUE TITLE
Crashes during registration, after generating keys

### ISSUE THREAD

**Issue by nomeata** [WhisperSystems/Signal-Android#5883]
With LibreSignal discontinued, I am trying to switch to vanilla Signal on my Jolla smartphone.

### Bug description
Signal crashes when trying to register.

### Steps to reproduce
- Install Signal on a Jolla Smartphone with Android Play Services installed (via Aptoid)
- Try to register a phone number using SMS
- Wait for that to timeout
- Use the offer to get a code via phone call
- Enter the phone call

**Actual result:** Signal crashes a moment after it put the green ✓ next to „Generating Keys“
**Expected result:** Key generated, registration complete

### Device info
**Device:** Jolla
**Android version:** 4.1.2 (alien dalvik)
**Signal version:** 3.22.2

### Debug log
```
Device  : unknown Jolla (alien_jolla_bionic)
Android : 4.1.2 (eng.erin.20151105.144423, JZO54K)
Memory  : 13M (17.32% free, 128M max)
Memclass: 128
OS Host : erin-ubuntu
App     : Signal 3.22.2

--------- beginning of /dev/log/system
E/AndroidRuntime( 6530): FATAL EXCEPTION: pool-7-thread-1
E/AndroidRuntime( 6530): java.lang.SecurityException: Not allowed to start service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms (has extras) } without permission com.google.android.c2dm.permission.RECEIVE
E/AndroidRuntime( 6530):        at android.app.ContextImpl.startService(ContextImpl.java:1167)
E/AndroidRuntime( 6530):        at android.content.ContextWrapper.startService(ContextWrapper.java:383)
E/AndroidRuntime( 6530):        at com.google.android.gms.gcm.GoogleCloudMessaging.zzy(Unknown Source)
E/AndroidRuntime( 6530):        at com.google.android.gms.gcm.GoogleCloudMessaging.register(Unknown Source)
E/AndroidRuntime( 6530):        at org.thoughtcrime.securesms.service.RegistrationService.handleCommonRegistration(RegistrationService.java:247)
E/AndroidRuntime( 6530):        at org.thoughtcrime.securesms.service.RegistrationService.handleVoiceRegistrationIntent(RegistrationService.java:166)
E/AndroidRuntime( 6530):        at org.thoughtcrime.securesms.service.RegistrationService.access$200(RegistrationService.java:63)
E/AndroidRuntime( 6530):        at org.thoughtcrime.securesms.service.RegistrationService$1.run(RegistrationService.java:97)
E/AndroidRuntime( 6530):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
E/AndroidRuntime( 6530):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
E/AndroidRuntime( 6530):        at java.lang.Thread.run(Thread.java:856)
--------- beginning of /dev/log/main
E/dalvikvm( 6825): Could not find class 'android.media.AudioAttributes$Builder', referenced from method org.thoughtcrime.securesms.notifications.MessageNotifier.sendInThreadNotification
E/dalvikvm( 6825): Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method org.thoughtcrime.securesms.ConversationListItem.setRippleColor
E/dalvikvm( 6825): Could not find class 'android.os.UserManager', referenced from method com.google.android.gms.common.GooglePlayServicesUtil.zzah
E/AndroidRuntime( 6825): FATAL EXCEPTION: pool-17-thread-1
E/AndroidRuntime( 6825): java.lang.SecurityException: Not allowed to start service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms (has extras) } without permission com.google.android.c2dm.permission.RECEIVE
E/AndroidRuntime( 6825):        at android.app.ContextImpl.startService(ContextImpl.java:1167)
E/AndroidRuntime( 6825):        at android.content.ContextWrapper.startService(ContextWrapper.java:383)
E/AndroidRuntime( 6825):        at com.google.android.gms.gcm.GoogleCloudMessaging.zzy(Unknown Source)
E/AndroidRuntime( 6825):        at com.google.android.gms.gcm.GoogleCloudMessaging.register(Unknown Source)
E/AndroidRuntime( 6825):        at org.thoughtcrime.securesms.service.RegistrationService.handleCommonRegistration(RegistrationService.java:247)
E/AndroidRuntime( 6825):        at org.thoughtcrime.securesms.service.RegistrationService.handleVoiceRegistrationIntent(RegistrationService.java:166)
E/AndroidRuntime( 6825):        at org.thoughtcrime.securesms.service.RegistrationService.access$200(RegistrationService.java:63)
E/AndroidRuntime( 6825):        at org.thoughtcrime.securesms.service.RegistrationService$1.run(RegistrationService.java:97)
E/AndroidRuntime( 6825):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
E/AndroidRuntime( 6825):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
E/AndroidRuntime( 6825):        at java.lang.Thread.run(Thread.java:856)
E/dalvikvm( 8516): Could not find class 'android.media.AudioAttributes$Builder', referenced from method org.thoughtcrime.securesms.notifications.MessageNotifier.sendInThreadNotification
E/dalvikvm( 8516): Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method org.thoughtcrime.securesms.ConversationListItem.setRippleColor
```

**Comment by 2-4601** [comment]
Thanks for the well written report. Signal requires Google Play Services for push, looks like an issue with that in your environment. Unfortunately Jolla/SailfishOS is not supported.

**Comment by haffenloher** [comment]
You need to install or update Signal after installing Play services so that Signal is granted the `com.google.android.c2dm.permission.RECEIVE` permission

**Comment by Trolldemorted** [comment]
@haffenloher is it not possible to request that permission at runtime? Signal should display an appropriate error message in case no play services are present/the permission is missing, not crash!

**Comment by nomeata** [comment]
> You need to install or update Signal after installing Play services so that Signal is granted the com.google.android.c2dm.permission.RECEIVE permission

Thanks, I’ll try that next!

**Comment by nomeata** [comment]
Confirmed. Re-installing signal helped. See http://www.joachim-breitner.de/blog/713-microG_on_Jolla for details of my struggle getting vanilla Signal working on my Jolla phone.

**Comment by moxie0** [comment]
Hey @nomeata we don't really have the resources to support Jolla devices. I wish you luck with your trouble shooting, would you be willing to take discussion about it to the forums? We try not to use GitHub for discussion, thanks.
