### ISSUE TITLE
Crash with UntrustedIdentityException after connecting to Signal Desktop

### ISSUE THREAD

**Issue by thejoelpatrol** [WhisperSystems/Signal-Android#5922]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
After attempting to pair with Signal Desktop, the Android app crashed while syncing, and now crashes immediately on launch every time, before any complete Activity is displayed (the screen is blank white at the time of crash). It seems similar to #5183, but the first exception in that case (related to the database) does *not* occur here. No contacts or messages are successfully synced with Desktop. It does not seem obviously related to #5744 or #5426. 

### Steps to reproduce
- Connect with Desktop app
- Start syncing between mobile and desktop

**Actual result:** Mobile app crashes during initial sync, and upon any subsequent launch, including when airplane mode is on
**Expected result:** App should open normally

### Screenshots
impossible to take

### Device info

**Device:** Samsung Galaxy S3 (US AT&T)
**Android version:** 6.0.1 (Cyanogenmod 13)
**Signal version:** 3.23.0
**SMS/MMS enabled**

### Debug log
via adb

```
12-03 21:00:58.949   641  1130 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.thoughtcrime.securesms/.RoutingActivity bnds=[159,1125][293,1280] (has extras)} from uid 10022 on display 0
12-03 21:00:59.032   641   671 W BroadcastQueue: Permission Denial: receiving Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$GmsExternalReceiver requires com.android.launcher3.permission.RECEIVE_LAUNCH_BROADCASTS due to sender com.cyanogenmod.trebuchet (uid 10022)
12-03 21:00:59.033   641   671 W BroadcastQueue: Permission Denial: broadcasting Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 (has extras) } from com.cyanogenmod.trebuchet (pid=1573, uid=10022) requires com.google.android.launcher.permission.RECEIVE_LAUNCH_BROADCASTS due to receiver com.google.android.gms/.icing.proxy.ApplicationLauncherReceiver
12-03 21:00:59.033   641   671 W BroadcastQueue: Permission Denial: broadcasting Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 (has extras) } from com.cyanogenmod.trebuchet (pid=1573, uid=10022) requires com.google.android.launcher.permission.RECEIVE_LAUNCH_BROADCASTS due to receiver com.google.android.googlequicksearchbox/com.google.android.apps.gsa.search.core.icingsync.ApplicationLaunchReceiver
12-03 21:00:59.086   641  3406 I ActivityManager: Start proc 14538:org.thoughtcrime.securesms/u0a106 for activity org.thoughtcrime.securesms/.RoutingActivity
12-03 21:00:59.276 14538 14538 W PartProvider: onCreate()
12-03 21:00:59.577 14538 14538 W PassphraseRequiredActionBarActivity: onCreate(null)
12-03 21:00:59.621 14538 14538 W ExperienceUpgradeActivity: getExperienceUpgrade(196)
12-03 21:00:59.629 14538 14538 W PassphraseRequiredActionBarActivity: routeApplicationState(), state: 0
12-03 21:00:59.649 14538 14538 W PassphraseRequiredActionBarActivity: initializeClearKeyReceiver()
12-03 21:00:59.710 14538 14538 W DirectoryRefreshListener: Scheduling for: 1480823565446
12-03 21:00:59.816 14538 14538 W PassphraseRequiredActionBarActivity: onResume()
12-03 21:00:59.853 14538 14573 D OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
12-03 21:00:59.882 14538 14538 W KeyCachingService: onCreate()
12-03 21:00:59.922 14538 14538 W service : Broadcasting new secret...
12-03 21:00:59.925 14538 14538 W KeyCachingService: onStartCommand, null
12-03 21:00:59.925 14538 14538 W KeyCachingService: onStartCommand, null
12-03 21:00:59.926 14538 14538 W KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
12-03 21:00:59.926 14538 14538 W KeyCachingService: Incrementing activity count...
12-03 21:00:59.970 14538 14538 W MessageRetrievalService: Active Count: 1
12-03 21:00:59.988 14538 14574 W MessageRetrievalService: Waiting for websocket state change....
12-03 21:00:59.989 14538 14574 W MessageRetrievalService: Network requirement: true, active activities: 1, push pending: 0
12-03 21:00:59.989 14538 14574 W MessageRetrievalService: Making websocket connection....
12-03 21:00:59.991 14538 14574 W WebSocketConnection: WSC connect()...
12-03 21:00:59.992 14538 14574 W OkHttpClientWrapper: Connecting to: wss://textsecure-service.whispersystems.org/v1/websocket/?login=%s&password=%s
12-03 21:00:59.998 14538 14574 W MessageRetrievalService: Network requirement: true, active activities: 1, push pending: 0
12-03 21:01:00.007 14538 14574 W MessageRetrievalService: Reading message...
12-03 21:01:00.028 14538 14573 W Adreno-GSL: <get_panel_settings:3802>: Android framework reported version 2. So, don't force ES30
12-03 21:01:00.028 14538 14573 I Adreno-EGL: <qeglDrvAPI_eglInitialize:381>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_KK_2.7_RB1.04.04.00.007.018_msm8960_KK_2.7_RB1_CL3869936_release_AU (CL3869936)
12-03 21:01:00.028 14538 14573 I Adreno-EGL: OpenGL ES Shader Compiler Version: 17.01.10.SPL
12-03 21:01:00.028 14538 14573 I Adreno-EGL: Build Date: 12/09/13 Mon
12-03 21:01:00.028 14538 14573 I Adreno-EGL: Local Branch: mybranch2092625
12-03 21:01:00.028 14538 14573 I Adreno-EGL: Remote Branch: quic/kk_2.7_rb1.15
12-03 21:01:00.028 14538 14573 I Adreno-EGL: Local Patches: NONE
12-03 21:01:00.028 14538 14573 I Adreno-EGL: Reconstruct Branch: AU_LINUX_ANDROID_KK_2.7_RB1.04.04.00.007.018 +  NOTHING
12-03 21:01:00.054 14538 14573 I OpenGLRenderer: Initialized EGL, version 1.4
12-03 21:01:00.344 14538 14560 W TextSecureSessionStore: No existing session information found.
12-03 21:01:00.380 14538 14560 W PushDecryptJob: org.whispersystems.libsignal.UntrustedIdentityException
12-03 21:01:00.380 14538 14560 W PushDecryptJob: 	at org.whispersystems.libsignal.SessionBuilder.process(SessionBuilder.java:105)
12-03 21:01:00.380 14538 14560 W PushDecryptJob: 	at org.whispersystems.libsignal.SessionCipher.decrypt(SessionCipher.java:172)
12-03 21:01:00.380 14538 14560 W PushDecryptJob: 	at org.whispersystems.libsignal.SessionCipher.decrypt(SessionCipher.java:142)
12-03 21:01:00.380 14538 14560 W PushDecryptJob: 	at org.whispersystems.signalservice.api.crypto.SignalServiceCipher.decrypt(SignalServiceCipher.java:140)
12-03 21:01:00.380 14538 14560 W PushDecryptJob: 	at org.whispersystems.signalservice.api.crypto.SignalServiceCipher.decrypt(SignalServiceCipher.java:114)
12-03 21:01:00.380 14538 14560 W PushDecryptJob: 	at org.thoughtcrime.securesms.jobs.PushDecryptJob.handleMessage(PushDecryptJob.java:139)
12-03 21:01:00.380 14538 14560 W PushDecryptJob: 	at org.thoughtcrime.securesms.jobs.PushDecryptJob.onRun(PushDecryptJob.java:119)
12-03 21:01:00.380 14538 14560 W PushDecryptJob: 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
12-03 21:01:00.380 14538 14560 W PushDecryptJob: 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
12-03 21:01:00.384 14538 14560 W JobConsumer: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
12-03 21:01:00.384 14538 14560 W JobConsumer: 	at org.whispersystems.libsignal.protocol.PreKeySignalMessage.<init>(PreKeySignalMessage.java:37)
12-03 21:01:00.384 14538 14560 W JobConsumer: 	at org.thoughtcrime.securesms.jobs.PushDecryptJob.handleUntrustedIdentityMessage(PushDecryptJob.java:591)
12-03 21:01:00.384 14538 14560 W JobConsumer: 	at org.thoughtcrime.securesms.jobs.PushDecryptJob.handleMessage(PushDecryptJob.java:178)
12-03 21:01:00.384 14538 14560 W JobConsumer: 	at org.thoughtcrime.securesms.jobs.PushDecryptJob.onRun(PushDecryptJob.java:119)
12-03 21:01:00.384 14538 14560 W JobConsumer: 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
12-03 21:01:00.384 14538 14560 W JobConsumer: 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
12-03 21:01:00.394 14538 14560 E AndroidRuntime: FATAL EXCEPTION: JobConsumer-0
12-03 21:01:00.394 14538 14560 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 14538
12-03 21:01:00.394 14538 14560 E AndroidRuntime: Theme: themes:{}
12-03 21:01:00.394 14538 14560 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
12-03 21:01:00.394 14538 14560 E AndroidRuntime: 	at org.whispersystems.libsignal.protocol.PreKeySignalMessage.<init>(PreKeySignalMessage.java:37)
12-03 21:01:00.394 14538 14560 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.PushDecryptJob.handleUntrustedIdentityMessage(PushDecryptJob.java:591)
12-03 21:01:00.394 14538 14560 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.PushDecryptJob.handleMessage(PushDecryptJob.java:178)
12-03 21:01:00.394 14538 14560 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.PushDecryptJob.onRun(PushDecryptJob.java:119)
12-03 21:01:00.394 14538 14560 E AndroidRuntime: 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
12-03 21:01:00.394 14538 14560 E AndroidRuntime: 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
12-03 21:01:00.396   641  1486 W ActivityManager:   Force finishing activity org.thoughtcrime.securesms/.RoutingActivity
12-03 21:01:00.481 14538 14575 W WebSocketConnection: onConnected()
12-03 21:01:00.489 14538 14569 W RecipientPreferenceDatabase: Muted until: 0
12-03 21:01:00.490 14538 14569 W RecipientPreferenceDatabase: Muted until: 0
12-03 21:01:00.555 14538 14584 W MmsSmsDatabase: Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, subscription_id, expires_in, expire_started, transport_type, attachment_id, unique_id, mid, data_size, _data, ct, cl, cd, name, pending_push FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, subscription_id, expires_in, expire_started, NULL AS network_failures, 'sms' AS transport_type, NULL AS unique_id, NULL AS mid, NULL AS data_size, NULL AS _data, NULL AS ct, NULL AS cl, NULL AS cd, NULL AS name, NULL AS pending_push FROM sms WHERE (read = 0) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'MMS::' || mms._id || '::' || date AS unique_row_id, part._id AS attachment_id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, subscription_id, expires_in, expire_started, network_failures, 'mms' AS transport_type, unique_id, NULL AS mid, data_size, NULL AS _data, ct, cl, cd, name, pending_push FROM mms LEFT OUTER JOIN part ON part._id =  (SELECT part._id FROM part WHERE part.mid = mms._id LIMIT 1) WHERE (read = 0) ORDER BY date_received ASC)
12-03 21:01:00.708   641  1486 I WindowManager: Screenshot max retries 4 of Token{41fda88 ActivityRecord{6ebb62b u0 org.thoughtcrime.securesms/.RoutingActivity t2532 f}} appWin=Window{d4ebfa3 u0 Starting org.thoughtcrime.securesms} drawState=4
```

**Comment by Trolldemorted** [comment]
I do not know what should happen during linking and what goes wrong here, but if either the jobmanager would catch exceptions or each job was wrapped in a try-catch block this and #5919 would not incapacitate Signal-Android completely.

**Comment by Trolldemorted** [comment]
Nevertheless, #5924 will stop your signal from crashing non-stop. Why you received such a message i cannot tell, so you should keep this issue open.

**Comment by Trolldemorted** [comment]
i am not convinced cb23e3a fixes this completely.

`hasLegacyMessage` only checks for a flag in the received protobuf message. What is stopping an adversary from setting that flag and using a zero-length legacy message? This way the adversary can still send remote Signal-Android clients into a crash-on-startup-loop.

**Comment by moxie0** [comment]
The flag is generated by the content of the serialized object. No field, no flag. Also the reason the code even gets to this point is because the content has been validated earlier, the bug was that we were acting on the wrong field instead of the field that had been validated.

**Comment by thejoelpatrol** [comment]
Thanks so much for this. I can confirm the affected device is now working again with 3.27.1
