### ISSUE TITLE
Image "stickers and scribbles" OOM error, preventable?

### ISSUE THREAD

**Issue by cascheberg** [WhisperSystems/Signal-Android#5969]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I was testing "Support for stickers and scribbles" (1b44bdcd3cafee26f08327f4ba6d9462d5713875) on a phone that has (only) 768MB of RAM.
The picture to be edited was a 3000 * 4000 pixel (w * h) ~1.9MB jpg. Tapping confirm after minimal editing resulted in a OOM error.

I got back to the conversation screen and conversation list by tapping the Android back button. Entering the conversation again from the conversation list then let me sent unsecured SMS only, which is a bad experience. Fortunately "force stop" Signal solves the issue.

I wonder if the process would succeed if pictures were scaled before editing? Sending the same picture without prior editing works as expected.

### Device info
**Device:** HTC Sensation XE
**Android version:** CyanogenMod 12.1 - Android 5.1.1
**Signal version:** 3.25.0

### Link to debug log
```
Alloc concurrent mark sweep GC freed 3(96B) AllocSpace objects, 0(0B) LOS objects, 9% free, 39MB/43MB, paused 4.333ms total 72.143ms
Throwing OutOfMemoryError "Failed to allocate a 24000012 byte allocation with 4194208 free bytes and 8MB until OOM"
Request threw uncaught throwable
  java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Failed to allocate a 24000012 byte allocation with 4194208 free bytes and 8MB until OOM
      at java.util.concurrent.FutureTask.report(FutureTask.java:93)
      at java.util.concurrent.FutureTask.get(FutureTask.java:163)
      at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor.afterExecute(FifoPriorityThreadPoolExecutor.java:96)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1120)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
      at java.lang.Thread.run(Thread.java:818)
      at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
   Caused by: java.lang.OutOfMemoryError: Failed to allocate a 24000012 byte allocation with 4194208 free bytes and 8MB until OOM
      at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
      at android.graphics.Bitmap.nativeCreate(Native Method)
      at android.graphics.Bitmap.createBitmap(Bitmap.java:812)
      at android.graphics.Bitmap.createBitmap(Bitmap.java:789)
      at android.graphics.Bitmap.createBitmap(Bitmap.java:756)
      at com.bumptech.glide.load.resource.bitmap.TransformationUtils.rotateImageExif(TransformationUtils.java:272)
      at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:167)
      at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:50)
      at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:19)
      at com.bumptech.glide.load.resource.bitmap.ImageVideoBitmapDecoder.decode(ImageVideoBitmapDecoder.java:39)
      at com.bumptech.glide.load.resource.bitmap.ImageVideoBitmapDecoder.decode(ImageVideoBitmapDecoder.java:20)
      at com.bumptech.glide.load.engine.DecodeJob.decodeFromSourceData(DecodeJob.java:190)
      at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:177)
      at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128)
      at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
      at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
      at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
      at java.lang.Thread.run(Thread.java:818) 
      at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118) 
```

I can provide more debug logs if relevant.

**Comment by moxie0** [comment]
Can you post the full debug log? Thanks!

**Comment by cascheberg** [comment]
Generating a debug log from within Signal is also not possible after the OOM, so here it is copied from Android Studio. (I could not find any sensitive information in there, I hope there really is none.) The log contains:
- conversation is open
- attach and edit image
- OOM
- go back to conversation screen
- go back to conversation list
- enter conversation again

Let me know if you need more or other data.
```
12-17 22:25:17.876 24082-24082/org.thoughtcrime.securesms W/ComposeMessageActivity: Selected: 1
12-17 22:25:17.898 24082-24082/org.thoughtcrime.securesms W/PassphraseRequiredActionBarActivity: onPause()
12-17 22:25:17.919 24082-24082/org.thoughtcrime.securesms W/KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
12-17 22:25:17.919 24082-24082/org.thoughtcrime.securesms W/KeyCachingService: Decrementing activity count...
12-17 22:25:17.920 24082-24082/org.thoughtcrime.securesms W/MessageRetrievalService: Active Count: 0
12-17 22:25:26.537 24082-24082/org.thoughtcrime.securesms W/ConversationActivity: onActivityResult called: 1, -1 , Intent { dat=content://com.android.providers.media.documents/document/image:373 flg=0x43 }
12-17 22:25:26.575 24082-24082/org.thoughtcrime.securesms W/PassphraseRequiredActionBarActivity: onResume()
12-17 22:25:26.656 24082-24082/org.thoughtcrime.securesms W/ThumbnailView: Not re-loading slide content://org.thoughtcrime.securesms/part/1482002542109/1
12-17 22:25:26.681 24082-24082/org.thoughtcrime.securesms W/KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
12-17 22:25:26.681 24082-24082/org.thoughtcrime.securesms W/KeyCachingService: Incrementing activity count...
12-17 22:25:26.684 24082-24082/org.thoughtcrime.securesms W/MessageRetrievalService: Active Count: 1
12-17 22:25:26.713 24082-24195/org.thoughtcrime.securesms W/AttachmentManager: slide with size 1922417 took 139ms
12-17 22:25:26.751 24082-24195/org.thoughtcrime.securesms W/MmsSmsDatabase: Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, subscription_id, expires_in, expire_started, transport_type, attachment_id, unique_id, mid, data_size, _data, thumbnail, ct, cl, cd, name, pending_push FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, subscription_id, expires_in, expire_started, NULL AS network_failures, 'sms' AS transport_type, NULL AS unique_id, NULL AS mid, NULL AS data_size, NULL AS _data, NULL AS thumbnail, NULL AS ct, NULL AS cl, NULL AS cd, NULL AS name, NULL AS pending_push FROM sms WHERE (read = 0) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'MMS::' || mms._id || '::' || date AS unique_row_id, part._id AS attachment_id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, subscription_id, expires_in, expire_started, network_failures, 'mms' AS transport_type, unique_id, mid, data_size, _data, thumbnail, ct, cl, cd, name, pending_push FROM mms LEFT OUTER JOIN part ON part._id =  (SELECT part._id FROM part WHERE part.mid = mms._id LIMIT 1) WHERE (read = 0) ORDER BY date_received ASC)
12-17 22:25:26.831 24082-24082/org.thoughtcrime.securesms W/ThumbnailView: loading part with id content://com.android.providers.media.documents/document/image%3A373, progress 1
12-17 22:25:27.142 24082-24082/org.thoughtcrime.securesms I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@3e9fb7bc time:26251566
12-17 22:25:29.214 24082-24082/org.thoughtcrime.securesms I/Timeline: Timeline: Activity_launch_request id:org.thoughtcrime.securesms time:26253638
12-17 22:25:29.250 24082-24082/org.thoughtcrime.securesms W/PassphraseRequiredActionBarActivity: onPause()
12-17 22:25:29.272 24082-24082/org.thoughtcrime.securesms W/KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
12-17 22:25:29.272 24082-24082/org.thoughtcrime.securesms W/KeyCachingService: Decrementing activity count...
12-17 22:25:29.273 24082-24082/org.thoughtcrime.securesms W/MessageRetrievalService: Active Count: 0
12-17 22:25:29.280 24082-24082/org.thoughtcrime.securesms W/PassphraseRequiredActionBarActivity: onCreate(null)
12-17 22:25:29.281 24082-24082/org.thoughtcrime.securesms W/ExperienceUpgradeActivity: getExperienceUpgrade(217)
12-17 22:25:29.282 24082-24082/org.thoughtcrime.securesms W/PassphraseRequiredActionBarActivity: routeApplicationState(), state: 0
12-17 22:25:29.284 24082-24082/org.thoughtcrime.securesms W/PassphraseRequiredActionBarActivity: initializeClearKeyReceiver()
12-17 22:25:29.423 24082-24082/org.thoughtcrime.securesms W/PassphraseRequiredActionBarActivity: onResume()
12-17 22:25:29.465 24082-24082/org.thoughtcrime.securesms W/KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
12-17 22:25:29.465 24082-24082/org.thoughtcrime.securesms W/KeyCachingService: Incrementing activity count...
12-17 22:25:29.467 24082-24082/org.thoughtcrime.securesms W/MessageRetrievalService: Active Count: 1
12-17 22:25:29.507 24082-24082/org.thoughtcrime.securesms I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@8e4113b time:26253930
12-17 22:25:32.488 24082-24090/org.thoughtcrime.securesms W/art: Suspending all threads took: 78.674ms
12-17 22:25:32.540 24082-24095/org.thoughtcrime.securesms I/art: Background partial concurrent mark sweep GC freed 13517(879KB) AllocSpace objects, 4(582KB) LOS objects, 15% free, 22MB/26MB, paused 7.995ms total 173.675ms
12-17 22:25:35.182 24082-24095/org.thoughtcrime.securesms I/art: Clamp target GC heap from 49MB to 48MB
12-17 22:25:35.676 24082-28608/org.thoughtcrime.securesms I/art: Alloc sticky concurrent mark sweep GC freed 34(608B) AllocSpace objects, 0(0B) LOS objects, 4% free, 45MB/47MB, paused 1.159ms total 7.537ms
12-17 22:25:35.736 24082-28608/org.thoughtcrime.securesms I/art: Clamp target GC heap from 49MB to 48MB
12-17 22:25:35.736 24082-28608/org.thoughtcrime.securesms I/art: Alloc partial concurrent mark sweep GC freed 9(288B) AllocSpace objects, 0(0B) LOS objects, 6% free, 45MB/48MB, paused 1.434ms total 54.016ms
12-17 22:25:35.835 24082-28608/org.thoughtcrime.securesms I/art: Clamp target GC heap from 49MB to 48MB
12-17 22:25:35.835 24082-28608/org.thoughtcrime.securesms I/art: Alloc concurrent mark sweep GC freed 6(12KB) AllocSpace objects, 0(0B) LOS objects, 6% free, 45MB/48MB, paused 1.678ms total 93.017ms
12-17 22:25:35.842 24082-28608/org.thoughtcrime.securesms I/art: Forcing collection of SoftReferences for 22MB allocation
12-17 22:25:35.924 24082-24090/org.thoughtcrime.securesms W/art: Suspending all threads took: 11.901ms
12-17 22:25:35.930 24082-28608/org.thoughtcrime.securesms I/art: Clamp target GC heap from 49MB to 48MB
12-17 22:25:35.930 24082-28608/org.thoughtcrime.securesms I/art: Alloc concurrent mark sweep GC freed 11(344B) AllocSpace objects, 0(0B) LOS objects, 6% free, 45MB/48MB, paused 3.967ms total 88.195ms
12-17 22:25:35.936 24082-28608/org.thoughtcrime.securesms E/art: Throwing OutOfMemoryError "Failed to allocate a 24000012 byte allocation with 3070692 free bytes and 2MB until OOM"
12-17 22:25:35.944 24082-28608/org.thoughtcrime.securesms I/art: Alloc sticky concurrent mark sweep GC freed 5(480B) AllocSpace objects, 0(0B) LOS objects, 4% free, 45MB/47MB, paused 1.129ms total 7.720ms
12-17 22:25:36.003 24082-28608/org.thoughtcrime.securesms I/art: Clamp target GC heap from 49MB to 48MB
12-17 22:25:36.003 24082-28608/org.thoughtcrime.securesms I/art: Alloc partial concurrent mark sweep GC freed 10(320B) AllocSpace objects, 0(0B) LOS objects, 6% free, 45MB/48MB, paused 1.281ms total 53.283ms
12-17 22:25:36.073 24082-28608/org.thoughtcrime.securesms I/art: Clamp target GC heap from 49MB to 48MB
12-17 22:25:36.073 24082-28608/org.thoughtcrime.securesms I/art: Alloc concurrent mark sweep GC freed 3(96B) AllocSpace objects, 0(0B) LOS objects, 6% free, 45MB/48MB, paused 1.342ms total 64.056ms
12-17 22:25:36.078 24082-28608/org.thoughtcrime.securesms I/art: Forcing collection of SoftReferences for 22MB allocation
12-17 22:25:36.143 24082-28608/org.thoughtcrime.securesms I/art: Clamp target GC heap from 49MB to 48MB
12-17 22:25:36.143 24082-28608/org.thoughtcrime.securesms I/art: Alloc concurrent mark sweep GC freed 3(96B) AllocSpace objects, 0(0B) LOS objects, 6% free, 45MB/48MB, paused 1.312ms total 64.056ms
12-17 22:25:36.148 24082-28608/org.thoughtcrime.securesms E/art: Throwing OutOfMemoryError "Failed to allocate a 24000012 byte allocation with 3070820 free bytes and 2MB until OOM"
12-17 22:25:36.151 24082-28608/org.thoughtcrime.securesms E/PriorityExecutor: Request threw uncaught throwable
                                                                              java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Failed to allocate a 24000012 byte allocation with 3070820 free bytes and 2MB until OOM
                                                                                  at java.util.concurrent.FutureTask.report(FutureTask.java:93)
                                                                                  at java.util.concurrent.FutureTask.get(FutureTask.java:163)
                                                                                  at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor.afterExecute(FifoPriorityThreadPoolExecutor.java:96)
                                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1120)
                                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                  at java.lang.Thread.run(Thread.java:818)
                                                                                  at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
                                                                               Caused by: java.lang.OutOfMemoryError: Failed to allocate a 24000012 byte allocation with 3070820 free bytes and 2MB until OOM
                                                                                  at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                                  at android.graphics.Bitmap.nativeCreate(Native Method)
                                                                                  at android.graphics.Bitmap.createBitmap(Bitmap.java:812)
                                                                                  at android.graphics.Bitmap.createBitmap(Bitmap.java:789)
                                                                                  at android.graphics.Bitmap.createBitmap(Bitmap.java:756)
                                                                                  at com.bumptech.glide.load.resource.bitmap.TransformationUtils.rotateImageExif(TransformationUtils.java:272)
                                                                                  at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:167)
                                                                                  at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:50)
                                                                                  at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:19)
                                                                                  at com.bumptech.glide.load.resource.bitmap.ImageVideoBitmapDecoder.decode(ImageVideoBitmapDecoder.java:39)
                                                                                  at com.bumptech.glide.load.resource.bitmap.ImageVideoBitmapDecoder.decode(ImageVideoBitmapDecoder.java:20)
                                                                                  at com.bumptech.glide.load.engine.DecodeJob.decodeFromSourceData(DecodeJob.java:190)
                                                                                  at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:177)
                                                                                  at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128)
                                                                                  at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
                                                                                  at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
                                                                                  at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
                                                                                  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                                  at java.lang.Thread.run(Thread.java:818) 
                                                                                  at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118) 
12-17 22:25:37.382 24082-32028/org.thoughtcrime.securesms W/WebSocketConnection: Sending keep alive...
12-17 22:25:37.537 24082-32027/org.thoughtcrime.securesms W/OkHttpClientWrapper: onMessage: BINARY
12-17 22:25:37.537 24082-32027/org.thoughtcrime.securesms W/WebSocketConnection: WSC onMessage()
12-17 22:25:37.537 24082-32027/org.thoughtcrime.securesms W/WebSocketConnection: Message Type: 2
12-17 22:25:47.903 24082-24082/org.thoughtcrime.securesms W/PassphraseRequiredActionBarActivity: onPause()
12-17 22:25:47.920 24082-24082/org.thoughtcrime.securesms W/KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
12-17 22:25:47.920 24082-24082/org.thoughtcrime.securesms W/KeyCachingService: Decrementing activity count...
12-17 22:25:47.920 24082-24082/org.thoughtcrime.securesms W/MessageRetrievalService: Active Count: 0
12-17 22:25:47.921 24082-24082/org.thoughtcrime.securesms W/ConversationActivity: onActivityResult called: 31424, 0 , null
12-17 22:25:47.923 24082-24082/org.thoughtcrime.securesms W/PassphraseRequiredActionBarActivity: onResume()
12-17 22:25:47.993 24082-24082/org.thoughtcrime.securesms W/ThumbnailView: Not re-loading slide content://org.thoughtcrime.securesms/part/1482002542109/1
12-17 22:25:48.008 24082-24082/org.thoughtcrime.securesms W/KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
12-17 22:25:48.008 24082-24082/org.thoughtcrime.securesms W/KeyCachingService: Incrementing activity count...
12-17 22:25:48.015 24082-24082/org.thoughtcrime.securesms W/MessageRetrievalService: Active Count: 1
12-17 22:25:48.114 24082-24082/org.thoughtcrime.securesms I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@3e9fb7bc time:26272537
12-17 22:25:48.371 24082-24082/org.thoughtcrime.securesms W/PassphraseRequiredActionBarActivity: onDestroy()
12-17 22:25:49.518 24082-24082/org.thoughtcrime.securesms W/ConversationActivity: onBackPressed()
12-17 22:25:49.523 24082-24082/org.thoughtcrime.securesms W/PassphraseRequiredActionBarActivity: onPause()
12-17 22:25:49.531 24082-24082/org.thoughtcrime.securesms W/KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
12-17 22:25:49.531 24082-24082/org.thoughtcrime.securesms W/KeyCachingService: Decrementing activity count...
12-17 22:25:49.532 24082-24082/org.thoughtcrime.securesms W/MessageRetrievalService: Active Count: 0
12-17 22:25:49.533 24082-24082/org.thoughtcrime.securesms W/PassphraseRequiredActionBarActivity: onResume()
12-17 22:25:49.585 24082-24082/org.thoughtcrime.securesms W/KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
12-17 22:25:49.585 24082-24082/org.thoughtcrime.securesms W/KeyCachingService: Incrementing activity count...
12-17 22:25:49.588 24082-24082/org.thoughtcrime.securesms W/MessageRetrievalService: Active Count: 1
12-17 22:25:49.660 24082-24082/org.thoughtcrime.securesms I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@fc531a7 time:26274083
12-17 22:25:49.830 24082-24082/org.thoughtcrime.securesms W/PassphraseRequiredActionBarActivity: onDestroy()
12-17 22:25:51.645 24082-24134/org.thoughtcrime.securesms W/MessageRetrievalService: Application level read timeout...
12-17 22:25:51.650 24082-24134/org.thoughtcrime.securesms W/MessageRetrievalService: Network requirement: true, active activities: 1, push pending: 0
12-17 22:25:51.654 24082-24134/org.thoughtcrime.securesms W/MessageRetrievalService: Reading message...
12-17 22:25:51.853 24082-24082/org.thoughtcrime.securesms I/Timeline: Timeline: Activity_launch_request id:org.thoughtcrime.securesms time:26276277
12-17 22:25:51.897 24082-24082/org.thoughtcrime.securesms W/PassphraseRequiredActionBarActivity: onPause()
12-17 22:25:51.943 24082-24082/org.thoughtcrime.securesms W/KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
12-17 22:25:51.943 24082-24082/org.thoughtcrime.securesms W/KeyCachingService: Decrementing activity count...
12-17 22:25:51.945 24082-24082/org.thoughtcrime.securesms W/MessageRetrievalService: Active Count: 0
12-17 22:25:51.952 24082-24082/org.thoughtcrime.securesms W/PassphraseRequiredActionBarActivity: onCreate(null)
12-17 22:25:51.957 24082-24082/org.thoughtcrime.securesms W/ExperienceUpgradeActivity: getExperienceUpgrade(217)
12-17 22:25:51.959 24082-24082/org.thoughtcrime.securesms W/PassphraseRequiredActionBarActivity: routeApplicationState(), state: 0
12-17 22:25:51.962 24082-24082/org.thoughtcrime.securesms W/PassphraseRequiredActionBarActivity: initializeClearKeyReceiver()
12-17 22:25:51.965 24082-24082/org.thoughtcrime.securesms W/ConversationActivity: onCreate()
12-17 22:25:51.965 24082-24082/org.thoughtcrime.securesms I/AppCompatDelegate: You should now use the AppCompatDelegate.FEATURE_SUPPORT_ACTION_BAR_OVERLAY id when requesting this feature.
12-17 22:25:52.033 24082-24082/org.thoughtcrime.securesms W/QuickAttachmentDrawer: updateControlsView()
12-17 22:25:52.320 24082-24082/org.thoughtcrime.securesms W/PassphraseRequiredActionBarActivity: onResume()
12-17 22:25:52.322 24082-24382/org.thoughtcrime.securesms W/MmsSmsDatabase: Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, subscription_id, expires_in, expire_started, transport_type, attachment_id, unique_id, mid, data_size, _data, thumbnail, ct, cl, cd, name, pending_push FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, subscription_id, expires_in, expire_started, NULL AS network_failures, 'sms' AS transport_type, NULL AS unique_id, NULL AS mid, NULL AS data_size, NULL AS _data, NULL AS thumbnail, NULL AS ct, NULL AS cl, NULL AS cd, NULL AS name, NULL AS pending_push FROM sms WHERE (thread_id = 1) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'MMS::' || mms._id || '::' || date AS unique_row_id, part._id AS attachment_id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, subscription_id, expires_in, expire_started, network_failures, 'mms' AS transport_type, unique_id, mid, data_size, _data, thumbnail, ct, cl, cd, name, pending_push FROM mms LEFT OUTER JOIN part ON part._id =  (SELECT part._id FROM part WHERE part.mid = mms._id LIMIT 1) WHERE (thread_id = 1) ORDER BY date_received DESC LIMIT 500)
12-17 22:25:52.352 24082-24082/org.thoughtcrime.securesms W/KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
12-17 22:25:52.352 24082-24082/org.thoughtcrime.securesms W/KeyCachingService: Incrementing activity count...
12-17 22:25:52.353 24082-24082/org.thoughtcrime.securesms W/MessageRetrievalService: Active Count: 1
12-17 22:25:52.371 24082-24082/org.thoughtcrime.securesms W/KeyboardAwareLinearLayout: rotation changed
12-17 22:25:52.371 24082-24082/org.thoughtcrime.securesms W/KeyboardAwareLinearLayout: onKeyboardClose()
12-17 22:25:52.394 24082-24082/org.thoughtcrime.securesms W/CameraView: skipping layout due to zero-width/height preview size
12-17 22:25:52.457 24082-24082/org.thoughtcrime.securesms W/ThumbnailView: loading part with id content://org.thoughtcrime.securesms/part/1482002542109/1, progress 0
12-17 22:25:52.468 24082-24082/org.thoughtcrime.securesms W/PhoneNumberFormatter: Got local CC: DE
12-17 22:25:52.631 24082-24082/org.thoughtcrime.securesms I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@3b13853 time:26277054
```

**Comment by moxie0** [comment]
Please trigger the bug, force close Signal, open Signal again, generate a debug log, and post the link here.  Thanks!

**Comment by cascheberg** [comment]
Here it is: https://gist.github.com/anonymous/43768e2423d4cd3a51b5bbb146f1b35b

**Comment by moxie0** [comment]
@cascheberg Thanks! Can you test master against your lowmem device?

**Comment by cascheberg** [comment]
Confirmed fixed!
