### ISSUE TITLE
AvatarDownloadJob NPE when trying to open Signal

### ISSUE THREAD

**Issue by haffenloher** [WhisperSystems/Signal-Android#5980]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Someone in a group tried to update the group avatar but apparently, something went wrong. Signal Desktop now shows a black avatar in the conversation list and the default avatar in the top bar, while Signal-Android crashes with a NPE in AvatarDownloadJob unless I go into airplane mode.

### Device info
**Android version:** 4.2.2
**Signal version:** 3.25.2

### Link to debug log

```
E/AndroidRuntime( 3089): FATAL EXCEPTION: JobConsumer-0
E/AndroidRuntime( 3089): java.lang.NullPointerException
E/AndroidRuntime( 3089): at org.thoughtcrime.securesms.jobs.AvatarDownloadJob.onRun(AvatarDownloadJob.java:73)
E/AndroidRuntime( 3089): at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
E/AndroidRuntime( 3089): at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
E/AndroidRuntime( 3089): at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
```

Full log: https://gist.github.com/haffenloher/977931ea330143a0cf8b41dea390ce04

**Comment by haffenloher** [comment]
confirmed, works 👍 thanks for the quick fix!
