### ISSUE TITLE
Group signal messages failing to send often

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/Signal-Android#5987]
I have:
- [ x] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Sending group signal messages is failing at a noticeably higher rate than before.
I have looked in my logs after other times this failed in the sam ostensible way. 
### Steps to reproduce
- send messages to a signal-only group enough times to see failures
- try to resend and it seems to keep failing.
- copy failed message text and paste into new message. Odds are it sends just fine. 

**Actual result:** Messages occasionally fail to send, sometimes even when resent
**Expected result:** Messages are sent fine most all the time.

### Device info
**Device:** Samsung Galaxy Note 5, LG g4
**Android version:** 6.0.1, 6.0.1 both stock verizon ROMs
**Signal version:** 3.25.3

### Link to debug log
https://gist.github.com/e230f7733c0e9ad89f86b82294ec32a0

I noticed the portion where the log looks to show errors. 
```
12-22 20:47:33.872 30538 30589 W PushServiceSocket: Push service URL: https://textsecure-service.whispersystems.org
12-22 20:47:33.872 30538 30589 W PushServiceSocket: Opening URL: https://textsecure-service.whispersystems.org/v1/messages/+*********76
12-22 20:47:33.882 30538 30589 W PushGroupSendJob: org.whispersystems.signalservice.api.push.exceptions.EncapsulatedExceptions
12-22 20:47:33.882 30538 30589 W PushGroupSendJob: 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:326)
12-22 20:47:33.882 30538 30589 W PushGroupSendJob: 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:147)
12-22 20:47:33.882 30538 30589 W PushGroupSendJob: 	at org.thoughtcrime.securesms.jobs.PushGroupSendJob.deliver(PushGroupSendJob.java:171)
12-22 20:47:33.882 30538 30589 W PushGroupSendJob: 	at org.thoughtcrime.securesms.jobs.PushGroupSendJob.onSend(PushGroupSendJob.java:85)
12-22 20:47:33.882 30538 30589 W PushGroupSendJob: 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:43)
12-22 20:47:33.882 30538 30589 W PushGroupSendJob: 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
12-22 20:47:33.882 30538 30589 W PushGroupSendJob: 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
12-22 20:47:33.882 30538 30589 W PushGroupSendJob: 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
12-22 20:47:33.882 30538 30589 W PhoneNumberFormatter: Got local CC: US
12-22 20:47:33.882 30538 30589 W PhoneNumberFormatter: Got local CC: US
12-22 20:47:33.912 30538 30589 W MmsSmsDatabase: Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, subscription_id, expires_in, expire_started, transport_type, attachment_id, unique_id, mid, data_size, _data, thumbnail, ct, cl, cd, name, pending_push FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, subscription_id, expires_in, expire_started, NULL AS network_failures, 'sms' AS transport_type, NULL AS unique_id, NULL AS mid, NULL AS data_size, NULL AS _data, NULL AS thumbnail, NULL AS ct, NULL AS cl, NULL AS cd, NULL AS name, NULL AS pending_push FROM sms WHERE (thread_id = 26) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'MMS::' || mms._id || '::' || date AS unique_row_id, part._id AS attachment_id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, subscription_id, expires_in, expire_started, network_failures, 'mms' AS transport_type, unique_id, mid, data_size, _data, thumbnail, ct, cl, cd, name, pending_push FROM mms LEFT OUTER JOIN part ON part._id =  (SELECT part._id FROM part WHERE part.mid = mms._id LIMIT 1) WHERE (thread_id = 26) ORDER BY date_received DESC LIMIT 1)
12-22 20:47:43.621 30538  4437 W WebSocketConnection: onConnected()
12-22 20:49:13.101 30538  5044 W OkHttpClientWrapper: java.io.EOFException
12-22 20:49:13.101 30538  5044 W OkHttpClientWrapper: 	at okio.RealBufferedSource.require(RealBufferedSource.java:64)
12-22 20:49:13.101 30538  5044 W OkHttpClientWrapper: 	at okio.RealBufferedSource.readByte(RealBufferedSource.java:77)
12-22 20:49:13.101 30538  5044 W OkHttpClientWrapper: 	at com.squareup.okhttp.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:130)
12-22 20:49:13.101 30538  5044 W OkHttpClientWrapper: 	at com.squareup.okhttp.internal.ws.WebSocketReader.readUntilNonControlFrame(WebSocketReader.java:119)
12-22 20:49:13.101 30538  5044 W OkHttpClientWrapper: 	at com.squareup.okhttp.internal.ws.WebSocketReader.readMessage(WebSocketReader.java:94)
12-22 20:49:13.101 30538  5044 W OkHttpClientWrapper: 	at com.squareup.okhttp.internal.ws.WebSocket$ReaderRunnable.execute(WebSocket.java:355)
12-22 20:49:13.101 30538  5044 W OkHttpClientWrapper: 	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
12-22 20:49:13.101 30538  5044 W OkHttpClientWrapper: 	at java.lang.Thread.run(Thread.java:818)
```

**Comment by JohnnyMT** [comment]
I can confirm this in my group chats.
It happens more often than before.
Also mentioned my group chat problems in #5891
