### ISSUE TITLE
Unregistering is broken in 3.26.0

### ISSUE THREAD

**Issue by moxie0** [WhisperSystems/Signal-Android#6018]
It seems that the 25.0.x support library is not compatible with the version of play services we're using:
https://stackoverflow.com/questions/40218025/gcm-unregister-causing-the-application-to-crash

`````
Caused by: java.lang.IllegalAccessError: Method 'void android.support.v4.content.ContextCompat.<init>()' is inaccessible to
                             class 'com.google.android.gms.iid.zzd' (declaration of 'com.google.android.gms.iid.zzd' appears in /data/data/org.thoughtc
                            rime.securesms/files/instant-run/dex/slice-com.google.android.gms-play-services-gcm-8.1.0_36a5849671bd3712febece8441146dd81
                            8a149b2-classes.dex)
                         E      at com.google.android.gms.iid.zzd.zzdo(Unknown Source)
                         E      at com.google.android.gms.iid.zzd.<init>(Unknown Source)
                         E      at com.google.android.gms.iid.zzd.<init>(Unknown Source)
                         E      at com.google.android.gms.iid.InstanceID.zza(Unknown Source)
                         E      at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
                         E      at com.google.android.gms.gcm.GoogleCloudMessaging.unregister(Unknown Source)
                         E      at org.thoughtcrime.securesms.preferences.AdvancedPreferenceFragment$PushMessagingClickListener$DisablePushMessagesTask
                            .doInBackground(AdvancedPreferenceFragment.java:209)
                         E      at org.thoughtcrime.securesms.preferences.AdvancedPreferenceFragment$PushMessagingClickListener$DisablePushMessagesTask
                            .doInBackground(AdvancedPreferenceFragment.java:163)
                         E      at android.os.AsyncTask$2.call(AsyncTask.java:295)
                         E      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                         E      ... 4 more
`````

**Comment by piratenpanda** [comment]
Any chances for an updated version with the fix? Hopefully it wont be too long until .1
