### ISSUE TITLE
Crash after sharing xlsx as jpg

### ISSUE THREAD

**Issue by s0riak** [WhisperSystems/Signal-Android#6061]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal crashes after sending a shared Excel-file (xlsx) which has been renamed to end with jpg. Afterwards it can't be used anymore.

### Steps to reproduce
- Rename a xyz.xlsx (Excel-File) to xyz.xlsx.jpg
- Share xyz.xlsx.jpg via signal to a contact
- Press the send button (The app crashes)
- Try to reopen the app

**Actual result:** The app crashes in step 3 and can't be opened afterwards (step 4). The apps can only be restored to work with deleting all data via the android settings.
**Expected result:** The best would be support xlsx files to be supported. The minimum requirement in my opinion is that the app rejects shared files that are not supported and doesn't keep crashing in this case.

### Screenshots
n.a.

### Device info
**Device:** Aquaris M5
**Android version:** 6.0.1
**Signal version:** 3.26.2

### Link to debug log
A debug log can't be captured as signal crashes immediately after any restart attemp.

**Comment by 2-4601** [comment]
Put your phone in airplane mode and you can probably start Signal without crashing. Then take a log. After that delete the message with the xlsx and disable air plane mode.
I remember there's a duplicate issue in on of the client trackers?

**Comment by moxie0** [comment]
Sorry about this but we can't really do much without a debug log, please reopen if you're able to get one using the steps @2-4601  provided, thanks!

**Comment by Trolldemorted** [comment]
We can do a lot with a good error report including steps to reproduce.

Here is the stacktrace of the crash:
```
W/JobConsumer: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference
                   at org.thoughtcrime.securesms.util.BitmapUtil.createScaledBytes(BitmapUtil.java:65)
                   at org.thoughtcrime.securesms.mms.MediaConstraints.getResizedMedia(MediaConstraints.java:78)
                   at org.thoughtcrime.securesms.jobs.SendJob.scaleAttachments(SendJob.java:69)
                   at org.thoughtcrime.securesms.jobs.PushMediaSendJob.deliver(PushMediaSendJob.java:122)
                   at org.thoughtcrime.securesms.jobs.PushMediaSendJob.onPushSend(PushMediaSendJob.java:69)
                   at org.thoughtcrime.securesms.jobs.PushSendJob.onSend(PushSendJob.java:64)
                   at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:43)
                   at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
                   at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
                   at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
W/MediaNetworkRequirement: part transfer progress is 2

                           --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: JobConsumer-4
                  Process: org.thoughtcrime.securesms, PID: 10313
                  java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference
                      at org.thoughtcrime.securesms.util.BitmapUtil.createScaledBytes(BitmapUtil.java:65)
                      at org.thoughtcrime.securesms.mms.MediaConstraints.getResizedMedia(MediaConstraints.java:78)
                      at org.thoughtcrime.securesms.jobs.SendJob.scaleAttachments(SendJob.java:69)
                      at org.thoughtcrime.securesms.jobs.PushMediaSendJob.deliver(PushMediaSendJob.java:122)
                      at org.thoughtcrime.securesms.jobs.PushMediaSendJob.onPushSend(PushMediaSendJob.java:69)
                      at org.thoughtcrime.securesms.jobs.PushSendJob.onSend(PushSendJob.java:64)
                      at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:43)
                      at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
                      at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
                      at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
```

PR #6080 mitigates this issue.
