### ISSUE TITLE
Crash when opening group conversations if video calling is enabled

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/Signal-Android#6137]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Upon returning back to the app after a video call crashed Signal.

### Steps to reproduce
- make a video call
- end call
- do something else
- open Signal

**Actual result:** crash
**Expected result:** no crash

I didn't super thoroughly test this but this happened after a video call on both devices. On one device I just let the screen turn off. Then when I opened it Signal crashed. On the other device I shared a link to Signal via Dropbox an when Signal opened it crashed.

### Device info
**Device:** Moto G4 Play
**Android version:** 6.0.1
**Signal version:** 3.29.0
**Log:** https://gist.github.com/ae124cf725c870d27e91f8a47336f598

**Device:** Nvidia K1
**Android version:** 6.0.1
**Signal version:** 3.29.0
**Log:** https://gist.github.com/d176d29cb5ba155536bc80935f0a6250

```
--------- beginning of crash
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 8616
E AndroidRuntime: java.lang.AssertionError: No options of default type!
E AndroidRuntime: 	at org.thoughtcrime.securesms.TransportOptions.getSelectedTransport(TransportOptions.java:97)
E AndroidRuntime: 	at org.thoughtcrime.securesms.TransportOptions.notifyTransportChangeListeners(TransportOptions.java:169)
E AndroidRuntime: 	at org.thoughtcrime.securesms.TransportOptions.setDefaultTransport(TransportOptions.java:57)
E AndroidRuntime: 	at org.thoughtcrime.securesms.components.SendButton.setDefaultTransport(SendButton.java:83)
E AndroidRuntime: 	at org.thoughtcrime.securesms.ConversationActivity.handleSecurityChange(ConversationActivity.java:833)
E AndroidRuntime: 	at org.thoughtcrime.securesms.ConversationActivity.access$1300(ConversationActivity.java:170)
E AndroidRuntime: 	at org.thoughtcrime.securesms.ConversationActivity$14.onPostExecute(ConversationActivity.java:974)
E AndroidRuntime: 	at org.thoughtcrime.securesms.ConversationActivity$14.onPostExecute(ConversationActivity.java:953)
E AndroidRuntime: 	at android.os.AsyncTask.finish(AsyncTask.java:651)
E AndroidRuntime: 	at android.os.AsyncTask.-wrap1(AsyncTask.java)
E AndroidRuntime: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:104)
E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5460)
E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
I Process : Sending signal. PID: 8616 SIG: 9
```

**Comment by 2-4601** [comment]
Dunno if this has anything to do with the video call.

It crashes every time I open a **group** conversation.

**Comment by schmeat** [comment]
I have the same thing. If I go to a group chat, the application will minimize itself. I am fairly sure that I am the only one in the group chat with the beta.

https://gist.github.com/anonymous/e7ada1a95ba4d7153f762ad359c6658f

**Comment by nrizzio** [comment]
@2-4601 if you disable video calling can you open the group conversation again?

**Comment by schmeat** [comment]
@nikolai-r It only occurs when the video option is enabled, for me.

**Comment by 2-4601** [comment]
Yeah, it seems to depend on the video calling option.

**Comment by moxie0** [comment]
in 3.29.0, not off to a great start!

**Comment by 2-4601** [comment]
Strange, I got this again in 3.29.2.

https://gist.github.com/31974c9ac043772fb6f2198fc380796e
```
AndroidRuntime: FATAL EXCEPTION: main
AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 19291
AndroidRuntime: java.lang.AssertionError: No options of default type!
AndroidRuntime: 	at org.thoughtcrime.securesms.TransportOptions.getSelectedTransport(TransportOptions.java:97)
AndroidRuntime: 	at org.thoughtcrime.securesms.TransportOptions.notifyTransportChangeListeners(TransportOptions.java:169)
AndroidRuntime: 	at org.thoughtcrime.securesms.TransportOptions.setDefaultTransport(TransportOptions.java:57)
AndroidRuntime: 	at org.thoughtcrime.securesms.components.SendButton.setDefaultTransport(SendButton.java:83)
AndroidRuntime: 	at org.thoughtcrime.securesms.ConversationActivity.handleSecurityChange(ConversationActivity.java:833)
AndroidRuntime: 	at org.thoughtcrime.securesms.ConversationActivity.access$1300(ConversationActivity.java:170)
AndroidRuntime: 	at org.thoughtcrime.securesms.ConversationActivity$14.onPostExecute(ConversationActivity.java:974)
AndroidRuntime: 	at org.thoughtcrime.securesms.ConversationActivity$14.onPostExecute(ConversationActivity.java:953)
AndroidRuntime: 	at android.os.AsyncTask.finish(AsyncTask.java:660)
AndroidRuntime: 	at android.os.AsyncTask.-wrap1(AsyncTask.java)
AndroidRuntime: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:677)
AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6120)
AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

I cannot reproduce this but here's how it happened once:
- I selected text in Firefox
- tapped SHARE
- chose Signal (I did not use direct share)
- Signal contact list showed up
- chose a group
- Signal crashed

Beta calling was enabled
