### ISSUE TITLE
Signal crashes when typing a message/moving cursor in message

### ISSUE THREAD

**Issue by skippy8472** [WhisperSystems/Signal-Android#6170]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When I am typing a message and moving the cursor around to fix a typo, every now and then the cursor is not responding as it should. You select a position in the message, try to delete a character (by hitting backspace). However not the character at which the cursor is pointing is removed, but the last one in the message. Continuing to correct most of the time results in a crash and restart of Signal.

A work around is to exit the message and go back to the entry screen (message saved as draft) opening it again and continue the message.

Not sure whether this is a quirk in the keyboard app or in Signal. I have not experienced this on my previous phone (Experia Z3 with Experia keyboard), so it might be keyboard related.

### Steps to reproduce
- Unfortunately I have not been able to come up with a sequence of steps to trigger this. A range of messages go OK and then for some reason this weird behaviour occurs.

**Actual result:**
Signal crashes

**Expected result:**
Signal should not crash on typing or correcting a message.

### Device info

**Device:** Motorola Z Play
**Android version:** 6.0.1
**Signal version:** 3.28.4
**Keyboad used:** GBoard - The Google Keyboard

### Link to debug log
https://gist.github.com/anonymous/ce4ebd92f92f5df67a55600d0ea68dde

**Comment by moxie0** [comment]
Looks like a keyboard issue to me:

```
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.Editor$SelectionStartHandleView.showAtLocation(int)' on a null object reference
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.widget.Editor$SelectionModifierCursorController.onTouchEvent(Editor.java:4889)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.widget.Editor.onTouchEvent(Editor.java:1223)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.widget.TextView.onTouchEvent(TextView.java:8304)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.view.View.dispatchTouchEvent(View.java:9303)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2556)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2556)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2556)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2556)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2556)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2556)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2556)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2556)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2556)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2556)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2556)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.app.Activity.dispatchTouchEvent(Activity.java:2775)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.view.View.dispatchPointerEvent(View.java:9523)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4242)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4108)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3654)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3707)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3673)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3799)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3681)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3856)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3654)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3707)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3673)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3681)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3654)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5969)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5908)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5869)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6072)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.os.MessageQueue.nativePollOnce(Native Method)
02-04 23:16:47.877  2113  2113 E MessageQueue-JNI: 	at android.os.MessageQueue.next(MessageQueue.java:323)
```

**Comment by skippy8472** [comment]
I changed the keyboard app and after that I no longer experienced any crashes.
So indeed this seems to be a keyboard issue.
Closing issue.
