### ISSUE TITLE
Registration crashes on Google-free emulator

### ISSUE THREAD

**Issue by nrizzio** [WhisperSystems/Signal-Android#6277]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When registering using a Google-free Android 6.0 emulator, the registration process crashes.

### Steps to reproduce
- Create an Android 6.0 emulator without Google APIs
- Build and install Signal from b43beaab752f1a1cb72ef3d464ccecfe8da9f593
- Go through the registration process, voice verification required in this case

**Actual result:** Registration crashes
**Expected result:** Registration doesn't crash

### Device info

**Device:** Emulated Nexus 5
**Android version:** 6.0
**Signal version:** 3.30.0 b43beaab752f1a1cb72ef3d464ccecfe8da9f593

### Link to debug log

The debug log isn't accessible, so here's the output of logcat:
```
02-21 21:43:51.761 7275-7556/org.thoughtcrime.securesms E/AndroidRuntime: FATAL EXCEPTION: pool-6-thread-1
                                                                          Process: org.thoughtcrime.securesms, PID: 7275
                                                                          com.google.protobuf.UninitializedMessageException: Message missing required fields: 
                                                                              at com.google.protobuf.AbstractMessage$Builder.newUninitializedMessageException(AbstractMessage.java:770)
                                                                              at org.whispersystems.libsignal.state.StorageProtos$PreKeyRecordStructure$Builder.build(StorageProtos.java:6875)
                                                                              at org.whispersystems.libsignal.state.PreKeyRecord.<init>(PreKeyRecord.java:31)
                                                                              at org.thoughtcrime.securesms.crypto.PreKeyUtil.generatePreKeys(PreKeyUtil.java:62)
                                                                              at org.thoughtcrime.securesms.service.RegistrationService.handleCommonRegistration(RegistrationService.java:248)
                                                                              at org.thoughtcrime.securesms.service.RegistrationService.handleVoiceRegistrationIntent(RegistrationService.java:172)
                                                                              at org.thoughtcrime.securesms.service.RegistrationService.access$200(RegistrationService.java:63)
                                                                              at org.thoughtcrime.securesms.service.RegistrationService$1.run(RegistrationService.java:102)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                              at java.lang.Thread.run(Thread.java:818)
```

**Comment by moxie0** [comment]
Crash has nothing to do with play services.  It looks as if you've somehow built Signal incorrectly, although I can't tell you how.

**Comment by nrizzio** [comment]
Alright, I'll close this for now, since the forum is probably the better place for it.

**Comment by haffenloher** [comment]
I think this is a duplicate of #5954 (check that thread for a solution)
