### ISSUE TITLE
Self-compiled Signal crashes when initiating call

### ISSUE THREAD

**Issue by vvug** [WhisperSystems/Signal-Android#6355]
Hello. I can compile Signal myself, everything seems to work, but when I try to initiate an encrypted call it crashes. This doesn't happen with the official apk (very strange!). I'm trying this with 3.31.1, and it's happening both on an emulated Nexus 5X (API 24, no gapps) and on a physical Nexus 6 with stock Android 7.1.1 (with gapps). The only difference is that the app on the emulator crashes immediately, while on the physical device can see (for a second or so) the calling screen. Here is the debug log of the crash from Android Studio for the emulated device:

```
03-10 11:11:58.132 3362-7710/org.thoughtcrime.securesms I/org.webrtc.Logging: PeerConnectionFactory: onNetworkThreadReady
03-10 11:11:58.132 3362-7711/org.thoughtcrime.securesms I/org.webrtc.Logging: PeerConnectionFactory: onWorkerThreadReady
03-10 11:11:58.133 3362-7712/org.thoughtcrime.securesms I/org.webrtc.Logging: PeerConnectionFactory: onSignalingThreadReady
03-10 11:11:58.138 3362-3362/org.thoughtcrime.securesms E/BluetoothAdapter: Bluetooth binder is null
03-10 11:11:58.139 3362-3362/org.thoughtcrime.securesms D/AndroidRuntime: Shutting down VM
03-10 11:11:58.139 3362-3362/org.thoughtcrime.securesms E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: org.thoughtcrime.securesms, PID: 3362
                                                                          java.lang.RuntimeException: Unable to create service org.thoughtcrime.securesms.service.WebRtcCallService: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.bluetooth.BluetoothAdapter.getProfileProxy(android.content.Context, android.bluetooth.BluetoothProfile$ServiceListener, int)' on a null object reference
                                                                              at android.app.ActivityThread.handleCreateService(ActivityThread.java:3172)
                                                                              at android.app.ActivityThread.-wrap5(ActivityThread.java)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1550)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:154)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                                           Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.bluetooth.BluetoothAdapter.getProfileProxy(android.content.Context, android.bluetooth.BluetoothProfile$ServiceListener, int)' on a null object reference
                                                                              at org.thoughtcrime.securesms.webrtc.audio.BluetoothStateManager.requestHeadsetProxyProfile(BluetoothStateManager.java:138)
                                                                              at org.thoughtcrime.securesms.webrtc.audio.BluetoothStateManager.<init>(BluetoothStateManager.java:52)
                                                                              at org.thoughtcrime.securesms.service.WebRtcCallService.initializeResources(WebRtcCallService.java:277)
                                                                              at org.thoughtcrime.securesms.service.WebRtcCallService.onCreate(WebRtcCallService.java:188)
                                                                              at android.app.ActivityThread.handleCreateService(ActivityThread.java:3162)
                                                                              at android.app.ActivityThread.-wrap5(ActivityThread.java) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1550) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:154) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
03-10 11:11:58.144 3362-7717/org.thoughtcrime.securesms E/WVMExtractor: Failed to open libwvm.so: dlopen failed: library "libwvm.so" not found
```

**Comment by vvug** [comment]
The debug log of the crash on the phone is different (still a NPE):

```
03-10 11:25:27.794 20646 20825 E AndroidRuntime: FATAL EXCEPTION: pool-10-thread-1
03-10 11:25:27.794 20646 20825 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 20646
03-10 11:25:27.794 20646 20825 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.webrtc.PeerConnection.addStream(org.webrtc.MediaStream)' on a null object reference
03-10 11:25:27.794 20646 20825 E AndroidRuntime: 	at org.thoughtcrime.securesms.webrtc.PeerConnectionWrapper.<init>(PeerConnectionWrapper.java:92)
03-10 11:25:27.794 20646 20825 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.WebRtcCallService$3.onSuccessContinue(WebRtcCallService.java:407)
03-10 11:25:27.794 20646 20825 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.WebRtcCallService$3.onSuccessContinue(WebRtcCallService.java:401)
03-10 11:25:27.794 20646 20825 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.WebRtcCallService$StateAwareListener.onSuccess(WebRtcCallService.java:1208)
03-10 11:25:27.794 20646 20825 E AndroidRuntime: 	at org.thoughtcrime.securesms.util.ListenableFutureTask.callback(ListenableFutureTask.java:103)
03-10 11:25:27.794 20646 20825 E AndroidRuntime: 	at org.thoughtcrime.securesms.util.ListenableFutureTask.access$100(ListenableFutureTask.java:28)
03-10 11:25:27.794 20646 20825 E AndroidRuntime: 	at org.thoughtcrime.securesms.util.ListenableFutureTask$2.run(ListenableFutureTask.java:91)
03-10 11:25:27.794 20646 20825 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-10 11:25:27.794 20646 20825 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-10 11:25:27.794 20646 20825 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
```

No files were changed on the Signal-Android git tree. I'm trying to build with Android Studio 2.3,

**Comment by johanw666** [comment]
I just tested it with 2 self compiled versions (3.31.1) on 2 Android phones, and everything works fine, except that I got some howling because the phones were next to each other. I called someone I knew had an iPhone, and got the old Redphone interface but also no crash.

**Comment by vvug** [comment]
@johanw666 Thanks for trying. The point is that it's definitely happening here. The crash is almost immediate, there's no need to actually answer the call in order to trigger it.

Are you building Signal with Android Studio?

**Comment by moxie0** [comment]
Does running the play release on the same device also crash?

**Comment by johanw666** [comment]
@vvug : yes, I am using Android Studio.

**Comment by vvug** [comment]
@moxie0 I just tried more carefully and I can reproduce it with the APK from Play store, in these conditions:
* Emulated device, Nexus 5X, Android 7
* Signal 3.31.0
* No Google Apps

**Comment by vvug** [comment]
Here is the debug log of the crash: https://gist.github.com/anonymous/3b6c3d39929e9967834a93d69f2d85ac
