### ISSUE TITLE
Crash on startup on Android 4.1.2 (java.lang.UnsatisfiedLinkError)

### ISSUE THREAD

**Issue by titodalcanton** [WhisperSystems/Signal-Android#6418]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal crashes on startup with the message "Unfortunately, Signal has stopped".

### Steps to reproduce
- Install Signal from https://signal.org/android/apk on Android 4.1.2
- Try to open it

**Actual result:** Signal shows a blank screen and quits after a few seconds, with the message "Unfortunately, Signal has stopped".
**Expected result:** Signal should either start and work (possibly with reduced capability, due to the old Android version) or provide a more useful error message explaining why it does not work. 

### Device info

**Device:** Samsung Galaxy Mini (GT-S5570)
**Android version:** 4.1.2
**Signal version:** 3.31.4

### Debug log

```
[…]
I/MultiDex( 1203): MultiDexExtractor.load(/mnt/asec/org.thoughtcrime.securesms-1/pkg.apk, false)
I/MultiDex( 1203): loading existing secondary dex files
I/MultiDex( 1203): load found 1 secondary dex files
I/MultiDex( 1203): install done
I/ActivityThread( 1203): Pub org.thoughtcrime.provider.securesms: org.thoughtcrime.securesms.providers.PartProvider
W/PartProvider( 1203): onCreate()
I/ActivityThread( 1203): Pub org.thoughtcrime.provider.securesms.mms: org.thoughtcrime.securesms.providers.MmsBodyProvider
I/dalvikvm( 1203): Could not find method android.provider.Telephony$Sms.getDefaultSmsPackage, referenced from method org.thoughtcrime.securesms.util.Util.isDefaultSmsPro
vider
W/dalvikvm( 1203): VFY: unable to resolve static method 1780: Landroid/provider/Telephony$Sms;.getDefaultSmsPackage (Landroid/content/Context;)Ljava/lang/String;
D/dalvikvm( 1203): VFY: replacing opcode 0x71 at 0x000a
I/dalvikvm( 1203): Could not find method android.app.ActivityManager.isLowRamDevice, referenced from method org.thoughtcrime.securesms.util.Util.isLowMemory
W/dalvikvm( 1203): VFY: unable to resolve virtual method 114: Landroid/app/ActivityManager;.isLowRamDevice ()Z
D/dalvikvm( 1203): VFY: replacing opcode 0x6e at 0x000e
W/PersistentAlarmManagerListener( 1203): class org.thoughtcrime.securesms.service.RotateSignedPreKeyListener scheduling for: 1490206667919
W/PersistentAlarmManagerListener( 1203): class org.thoughtcrime.securesms.service.DirectoryRefreshListener scheduling for: 1490077067937
W/PersistentAlarmManagerListener( 1203): class org.thoughtcrime.securesms.service.UpdateApkRefreshListener scheduling for: 1490055467962
W/dalvikvm( 1203): No implementation found for native Lorg/webrtc/PeerConnectionFactory;.initializeAndroidGlobals:(Ljava/lang/Object;ZZZ)Z
D/AndroidRuntime( 1203): Shutting down VM
W/dalvikvm( 1203): threadid=1: thread exiting with uncaught exception (group=0x40aba300)
E/AndroidRuntime( 1203): FATAL EXCEPTION: main
E/AndroidRuntime( 1203): java.lang.UnsatisfiedLinkError: Native method not found: org.webrtc.PeerConnectionFactory.initializeAndroidGlobals:(Ljava/lang/Object;ZZZ)Z
E/AndroidRuntime( 1203):        at org.webrtc.PeerConnectionFactory.initializeAndroidGlobals(Native Method)
E/AndroidRuntime( 1203):        at org.thoughtcrime.securesms.ApplicationContext.onCreate(ApplicationContext.java:94)
E/AndroidRuntime( 1203):        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:999)
E/AndroidRuntime( 1203):        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4336)
E/AndroidRuntime( 1203):        at android.app.ActivityThread.access$1300(ActivityThread.java:142)
E/AndroidRuntime( 1203):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1268)
E/AndroidRuntime( 1203):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 1203):        at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 1203):        at android.app.ActivityThread.main(ActivityThread.java:4931)
E/AndroidRuntime( 1203):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 1203):        at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 1203):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
E/AndroidRuntime( 1203):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:558)
E/AndroidRuntime( 1203):        at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  342):   Force finishing activity org.thoughtcrime.securesms/.RoutingActivity
W/ActivityManager(  342): Activity pause timeout for ActivityRecord{410d1910 org.thoughtcrime.securesms/.RoutingActivity}
W/ActivityManager(  342): Activity destroy timeout for ActivityRecord{410d1910 org.thoughtcrime.securesms/.RoutingActivity}
```

**Comment by moxie0** [comment]
looks like it's not correctly loading the shared library for some reason. you running a custom rom or otherwise fucked up phone?

**Comment by titodalcanton** [comment]
It is indeed a custom ROM and I am running Signal from the SD card, if that matters.

**Comment by moxie0** [comment]
There's probably something going on there, either with the ROM or the SD card (Signal isn't supposed to be able to run from the SD card).  We're calling System.loadLibrary and it's not loading correctly, there's not really anything else we can do.  If you have a non-production setup I'm afraid you'll have to diagnose why basic Android functionality is failing yourself.  Sorry!
