### ISSUE TITLE
[Crash] Signal crash and makes the phone restart if locking the phone while Signal is on foreground

### ISSUE THREAD

**Issue by Carnageman** [WhisperSystems/Signal-Android#6823]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
If I lock the phone while Signal is on the foreground, Signal crash and makes my whole phone OS restart. If I reduce Signal so it runs on the background and I lock the phone, it locks normally.

### Steps to reproduce
- Open Signal
- Push the lock button on the phone

**Actual result:** Phone crash and restart automatically.
**Expected result:** Phone should lock and sleep.

### Device info

**Device:** Wiko BIRDY
**Android version:** 4.4.2
**Signal version:** Built from sources on this repository

### Link to debug log

I tried to catch the crash on the logs of Signal, but nothing showed up in the logs. But, I did some analysis via logcats : [ADB logcat logs](https://github.com/WhisperSystems/Signal-Android/files/1176674/error_android_signal_more.txt)

It seems that the curious stuff happens here :

```
07-26 15:12:10.186 12279-12279/? E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -19
07-26 15:12:10.845 12279-12279/? E/[EGL-ERROR]: void __egl_platform_dequeue_buffer(egl_surface*):1779: failed to dequeue buffer from native window 0x62fde660; err = -19, buf = 0x0,max_allowed_dequeued_buffers 3
07-26 15:12:10.849 12279-12279/? W/MALI: __egl_mali_post_to_window_surface:1056: __egl_mali_post_to_window_surface: posting to window surface failed; couldn't acquire output buffer (surface=0x623bdff8)
07-26 15:12:10.853 12279-12279/? W/MALI: __egl_set_error:121: [WARNING]Mali EGL errorcode: 300d
07-26 15:12:10.853 12279-12279/? W/HardwareRenderer: EGL error: EGL_BAD_SURFACE
07-26 15:12:10.855 12279-12279/? W/HardwareRenderer: Mountain View, we've had a problem here. Switching back to software rendering.
07-26 15:12:11.162 12279-12279/? E/ViewRootImpl: Could not lock surface
                                                 java.lang.IllegalArgumentException
                                                     at android.view.Surface.nativeLockCanvas(Native Method)
                                                     at android.view.Surface.lockCanvas(Surface.java:243)
                                                     at android.view.ViewRootImpl.drawSoftware(ViewRootImpl.java:2783)
                                                     at android.view.ViewRootImpl.draw(ViewRootImpl.java:2754)
                                                     at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2591)
                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2214)
                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1192)
                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6229)
                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:591)
                                                     at android.view.Choreographer.doFrame(Choreographer.java:560)
                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
                                                     at android.os.Handler.handleCallback(Handler.java:808)
                                                     at android.os.Handler.dispatchMessage(Handler.java:103)
                                                     at android.os.Looper.loop(Looper.java:193)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5315)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
                                                     at dalvik.system.NativeStart.main(Native Method)
```

**Comment by moxie0** [comment]
Unfortunately if your entire OS is crashing, there's nothing we can do from Signal. The stack trace from that log doesn't have any of our code in it, looks like a ROM bug to me.
