### ISSUE TITLE
v4.9.2 crashes on startup

### ISSUE THREAD

**Issue by grendello** [WhisperSystems/Signal-Android#6846]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
As a follow up to issue https://github.com/WhisperSystems/Signal-Android/issues/6838, v4.9.2 still crashes on startup (I'm not even getting the "app failed to start" dialog, the UI flashes and then disappears). The stack trace of the SQL crash is similar to the original one posted in https://github.com/WhisperSystems/Signal-Android/issues/6838#issuecomment-319319167:

```
08-02 08:41:40.027 30835 30856 W DatabaseHelper:
08-02 08:41:40.027 30835 30856 W DatabaseHelper: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: recipient_preferences.recipient_ids (code 2067)
08-02 08:41:40.027 30835 30856 W DatabaseHelper: 	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
08-02 08:41:40.027 30835 30856 W DatabaseHelper: 	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:734)
08-02 08:41:40.027 30835 30856 W DatabaseHelper: 	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
08-02 08:41:40.027 30835 30856 W DatabaseHelper: 	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
08-02 08:41:40.027 30835 30856 W DatabaseHelper: 	at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1606)
08-02 08:41:40.027 30835 30856 W DatabaseHelper: 	at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1552)
08-02 08:41:40.027 30835 30856 W DatabaseHelper: 	at org.thoughtcrime.securesms.database.DatabaseFactory$DatabaseHelper.onUpgrade(DatabaseFactory.java:1007)
08-02 08:41:40.027 30835 30856 W DatabaseHelper: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256)
08-02 08:41:40.027 30835 30856 W DatabaseHelper: 	at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
08-02 08:41:40.027 30835 30856 W DatabaseHelper: 	at org.thoughtcrime.securesms.database.SmsDatabase.getExpirationStartedMessages(SmsDatabase.java:654)
08-02 08:41:40.027 30835 30856 W DatabaseHelper: 	at org.thoughtcrime.securesms.service.ExpiringMessageManager$LoadTask.run(ExpiringMessageManager.java:57)
08-02 08:41:40.027 30835 30856 W DatabaseHelper: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
08-02 08:41:40.027 30835 30856 W DatabaseHelper: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
08-02 08:41:40.027 30835 30856 W DatabaseHelper: 	at java.lang.Thread.run(Thread.java:761)
08-02 08:41:40.028 30835 30856 E SQLiteLog: (1) no such table: recipient_preference
08-02 08:41:40.028 30835 30856 I SQLiteConnectionPool: The connection pool for /data/user/0/org.thoughtcrime.securesms/databases/messages.db has been closed but there are still 1 connections in use.  They will be closed as they are released back to the pool.
08-02 08:41:40.029 30835 30856 E AndroidRuntime: FATAL EXCEPTION: pool-2-thread-1
08-02 08:41:40.029 30835 30856 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 30835
08-02 08:41:40.029 30835 30856 E AndroidRuntime: android.database.sqlite.SQLiteException: no such table: recipient_preference (code 1): , while compiling: DELETE FROM recipient_preference WHERE _id = ?
08-02 08:41:40.029 30835 30856 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
08-02 08:41:40.029 30835 30856 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
08-02 08:41:40.029 30835 30856 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
08-02 08:41:40.029 30835 30856 E AndroidRuntime: 	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
08-02 08:41:40.029 30835 30856 E AndroidRuntime: 	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
08-02 08:41:40.029 30835 30856 E AndroidRuntime: 	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
08-02 08:41:40.029 30835 30856 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.delete(SQLiteDatabase.java:1526)
08-02 08:41:40.029 30835 30856 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.DatabaseFactory$DatabaseHelper.onUpgrade(DatabaseFactory.java:1010)
08-02 08:41:40.029 30835 30856 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256)
08-02 08:41:40.029 30835 30856 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
08-02 08:41:40.029 30835 30856 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.SmsDatabase.getExpirationStartedMessages(SmsDatabase.java:654)
08-02 08:41:40.029 30835 30856 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.ExpiringMessageManager$LoadTask.run(ExpiringMessageManager.java:57)
08-02 08:41:40.029 30835 30856 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
08-02 08:41:40.029 30835 30856 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
08-02 08:41:40.029 30835 30856 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
08-02 08:41:40.029 30835 30856 D AppTracker: App Event: crash
```

The second exception above appears to be caused by a typo in the table name.

### Steps to reproduce
- upgrade to v4.9.2 and try to start the app

### Device info

**Device:** OnePlus 3T
**Android version:** 7.1.1
**Signal version:** 4.9.2

**Comment by nrizzio** [comment]
Here's the offending line: https://github.com/WhisperSystems/Signal-Android/blob/9a55632202576de468161a1e5002e35078c213ee/src/org/thoughtcrime/securesms/database/DatabaseFactory.java#L1010
