### ISSUE TITLE
v4.9.4 crash at startup

### ISSUE THREAD

**Issue by globaluar** [WhisperSystems/Signal-Android#6850]
I have:
- [x ] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
As another follow up to the issues #6846 and #6838 for me the crash on startup still persists.
Before crashing during startup "Updating database" is displayed very quickly.

`adb logcat` shows the following:
```
--------- beginning of crash
08-03 06:39:53.102  8610  8635 E AndroidRuntime: FATAL EXCEPTION: pool-2-thread-1
08-03 06:39:53.102  8610  8635 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 8610
08-03 06:39:53.102  8610  8635 E AndroidRuntime: java.lang.AssertionError: Unable to resolve: 
08-03 06:39:53.102  8610  8635 E AndroidRuntime: 	at  org.thoughtcrime.securesms.database.DatabaseFactory$DatabaseHelper.onUpgrade(DatabaseFactory.java:1001)
08-03 06:39:53.102  8610  8635 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256)
08-03 06:39:53.102  8610  8635 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
08-03 06:39:53.102  8610  8635 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.SmsDatabase.getExpirationStartedMessages(SmsDatabase.java:654)
08-03 06:39:53.102  8610  8635 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.ExpiringMessageManager$LoadTask.run(ExpiringMessageManager.java:57)
08-03 06:39:53.102  8610  8635 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
08-03 06:39:53.102  8610  8635 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
08-03 06:39:53.102  8610  8635 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
08-03 06:39:53.431  1042  5998 I chatty  : uid=1000(system) Binder:1042_B expire 6 lines
08-03 06:39:53.474  1042  5961 I chatty  : uid=1000(system) Binder:1042_9 expire 19 lines
08-03 06:39:54.809  1042  6008 I chatty  : uid=1000(system) Binder:1042_D expire 11 lines
08-03 06:39:55.532  1042  1098 I chatty  : uid=1000(system) android.display expire 2 lines
08-03 06:39:59.460  8939  8986 E AndroidRuntime: FATAL EXCEPTION: pool-2-thread-1
08-03 06:39:59.460  8939  8986 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 8939
08-03 06:39:59.460  8939  8986 E AndroidRuntime: java.lang.AssertionError: Unable to resolve: 
08-03 06:39:59.460  8939  8986 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.DatabaseFactory$DatabaseHelper.onUpgrade(DatabaseFactory.java:1001)
08-03 06:39:59.460  8939  8986 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256)
08-03 06:39:59.460  8939  8986 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
08-03 06:39:59.460  8939  8986 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.SmsDatabase.getExpirationStartedMessages(SmsDatabase.java:654)
08-03 06:39:59.460  8939  8986 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.ExpiringMessageManager$LoadTask.run(ExpiringMessageManager.java:57)
08-03 06:39:59.460  8939  8986 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
08-03 06:39:59.460  8939  8986 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
08-03 06:39:59.460  8939  8986 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
```

### Steps to reproduce

- upgrade to version between 4.9.1 and 4.9.4 and start Signal

### Device info

**Device:** OnePlus 2
**Android version:** 7.1.2 (LineageOS)
**Signal version:** 4.9.4

**Comment by johanw666** [comment]
recipientIds appears to be empty. The current code would indeed give an assertion error in that case.

**Comment by moxie0** [comment]
@globaluar Could you update to this APK and paste the ADB output from it? Should still crash, but will provide a little more info: https://mega.nz/#!QwMEzIgK!Gt9gRPysjJU4nyewyvf9MtqNiM4fjVjjHb-fNRl-jYc

**Comment by Adalan** [comment]
I'm having an issue on startup. It loads up, shows me my inbox, and then instantly crashes. If I don't click on the "Close App" button, I see it syncing all my missed messages. Desktop still works during this.

**Comment by moxie0** [comment]
@Adalan I would need a debug log in order to help, please open a new issue with a log if it's different from what's above.

**Comment by Adalan** [comment]
If I don't have access to adb or rooted, is there another way to get you the log? I've been sending feedback when the crash happens including the system log. Otherwise, I'll have to wait until sometime tonight.

**Comment by moxie0** [comment]
@Adalan Unfortunately adb logcat is probably the only way in a situation like this =(. I *may* eventually get the crash report through the play store, but it can take days

**Comment by Adalan** [comment]
Ok, I've just wiped data and re-setup. When I get home tonight, if it's crashing again, I'll take a capture. Thanks!

**Comment by globaluar** [comment]
Sorry for the late reply, but unfortunatelly I wasn't able to make it earlier.
The update 4.9.5 solved the issue for me
Thanks for the fast reply
