### ISSUE TITLE
Signal 4.10.11 crashes when opening group on Alien Dalvik

### ISSUE THREAD

**Issue by sirhcel** [WhisperSystems/Signal-Android#6987]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal crashes with the _"Signal" has stopped unexpectedly_ when opening a group on Jolla/Alien Dalvik.

It looks to me that this happend due to a method missing in that implemementation. `Configuration.getLayoutDirection()` is API level 17 while the actual Aliend Dalvik provides Android 4.1.2 with API level 16. So this is is no bug in Signal but having a workaround would help Jolla users to use vanilla Signal on their device.

### Steps to reproduce
- Start signal
- Open a group

**Actual result:** Signal crashes with the message _"Signal" has stopped unexpectedly_
**Expected result:** Group should open as they did with Signal 4.9.5

### Device info
**Device:** Jolla (alien_jolla_bionic)
**Android version:** 4.1.2 (Alien Dalvik)
**Signal version:** 4.10.11

### Debug log
```
Device  : unknown Jolla (alien_jolla_bionic)
Android : 4.1.2 (eng.erin.20151105.144423, JZO54K)
Memory  : 26M (20.48% free, 256M max)
Memclass: 128
OS Host : erin-ubuntu
App     : Signal 4.10.11
```
```
[nemo@Sailfish ~]$ devel-su journalctl -a -f
[...]
Sep 24 16:06:16 Sailfish start_alien.sh[1608]: 09-24 16:06:16.094  3812  3812 E dalvikvm: Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method android.support.v7.widget.AppCompatImageHelper.hasOverlappingRendering
[...]
Sep 24 16:06:16 Sailfish start_alien.sh[1608]: 09-24 16:06:16.597  3812  3841 E dalvikvm: Could not find class 'android.media.AudioAttributes$Builder', referenced from method org.thoughtcrime.securesms.notifications.MessageNotifier.sendInThreadNotification
Sep 24 16:06:16 Sailfish start_alien.sh[1608]: 09-24 16:06:16.982  3812  3812 E dalvikvm: Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method org.thoughtcrime.securesms.ConversationListItem.setRippleColor
[...]
Sep 24 16:06:25 Sailfish start_alien.sh[1608]: 09-24 16:06:25.784  3812  3812 E AndroidRuntime: FATAL EXCEPTION: main
Sep 24 16:06:25 Sailfish start_alien.sh[1608]: 09-24 16:06:25.784  3812  3812 E AndroidRuntime: java.lang.NoSuchMethodError: android.content.res.Configuration.getLayoutDirection
Sep 24 16:06:25 Sailfish start_alien.sh[1608]: 09-24 16:06:25.784  3812  3812 E AndroidRuntime:     at org.thoughtcrime.securesms.util.DynamicLanguage.getLayoutDirection(DynamicLanguage.java:48)
Sep 24 16:06:25 Sailfish start_alien.sh[1608]: 09-24 16:06:25.784  3812  3812 E AndroidRuntime:     at org.thoughtcrime.securesms.ConversationItem.onLayout(ConversationItem.java:225)
Sep 24 16:06:25 Sailfish start_alien.sh[1608]: 09-24 16:06:25.784  3812  3812 E AndroidRuntime:     at android.view.View.layout(View.java:13780)
[...]
```

**Comment by sirhcel** [comment]
Thank you very much @moxie0! a39d9bf works like a charm. :)
