### ISSUE TITLE
4.11.3: Read receipts working intermittently

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/Signal-Android#7082]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
While in conversation, some messages get blue check marks, some don't

### Steps to reproduce
- Conversation includes: 1 android 4.11.3 linked to one desktop 0.43.4, 1 other android linked to a desktop 0.43.4
- Normal conversation back and forth

**Actual result:** Some messages get blue checks, some don't
**Expected result:** All messages that are read get marked blue eventually.

### Device info

**Device:** galaxy s8, galaxy note 8
**Android version:** 7.0, 7.1
**Signal version:** 4.11.3 on both, 0.43.4 desktop on both

### Link to debug log
S8 logs:
https://gist.github.com/124db7453c7d988e8b59a3debc5860be
https://gist.github.com/25b7f341e2a170ede0d3c6ee0badb223

desktop 0.43.4 linked from S8 logs:
https://gist.github.com/9735401324e89c79fbbcb7d8c3a8c184
Lots of this in there:
`2017-10-11T14:47:36.206Z queueEnvelope error handling envelope +[REDACTED]776.1 1507733255543 : Error: Unsupported content message
    at MessageReceiver.innerHandleContentMessage (chrome-extension://bikioccmkafdpakkkcpdbppfkghcmihk/js/libtextsecure.js:38736:19)
    at MessageReceiver.<anonymous> (chrome-extension://bikioccmkafdpakkkcpdbppfkghcmihk/js/libtextsecure.js:38723:25)
    at <anonymous>`

**Comment by jeremymasters** [comment]
Rebooted the Note 8 and it worked for a few messages, then stopped going blue again.
