### ISSUE TITLE
Android 4.14 FC on launch 

### ISSUE THREAD

**Issue by jwchips** [WhisperSystems/Signal-Android#7234]
Signal crashes/force closes when launched 

### Device info

**Device:** xiaomi redmi 4x (santoni) 
**Android version:** 7.1.2
**Signal version:** 4.14.0

### Link to debug log

android.os.FileUriExposedException: file:///storage/emulated/0/MIUI/ringtone/Archer%20Pirate%20Virus%20ringtone.mp3 exposed beyond app through Notification.sound
	at android.os.StrictMode.onFileUriExposed(StrictMode.java:1796)
	at android.net.Uri.checkFileUriExposed(Uri.java:2346)
	at android.app.NotificationManager.notifyAsUser(NotificationManager.java:300)
	at android.app.NotificationManager.notify(NotificationManager.java:284)
	at android.support.v4.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:210)
	at android.support.v4.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:194)
	at org.thoughtcrime.securesms.notifications.MessageNotifier.sendSingleThreadNotification(MessageNotifier.java:341)
	at org.thoughtcrime.securesms.notifications.MessageNotifier.updateNotification(MessageNotifier.java:274)
	at org.thoughtcrime.securesms.notifications.MessageNotifier.updateNotification(MessageNotifier.java:232)
	at org.thoughtcrime.securesms.notifications.MessageNotifier.updateNotification(MessageNotifier.java:203)
	at org.thoughtcrime.securesms.jobs.SmsReceiveJob.onRun(SmsReceiveJob.java:66)
	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)

**Comment by moxie0** [comment]
Huh interesting, seems like a targetSdk thing. I take it you added a ringtone to Signal through the ringtone selector thing? Thanks for being a beta tester!

**Comment by jwchips** [comment]
Ringtone was set many moons ago but I believe it was set using the option within signals notification settings. This launches the stock file explorer/picker but I suspect I launched my default file manager from the hamburger menu and actually found the file through that

Signal - settings - notifications - sound - add new ringtone - launch solid Explorer from hamburger menu - select file

I've reset the notification sound using the default file picker and the issue
